In [1]:
import pandas as pd

In [50]:
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/iris.csv')

In [3]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [ ]:
df['species'].replace({'setosa': 0, 'versicolor': 1, 'virginica': 2},
                       inplace = True)

C:\Users\linde\AppData\Local\Temp\ipykernel_7444\405888724.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'].replace({


In [6]:
df['species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [9]:
# Data Load
from sklearn import datasets

iris = datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [10]:
X = iris.data
y = iris.target

In [13]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [16]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [18]:
from sklearn.tree import DecisionTreeClassifier as DTC
dt = DTC(random_state=1)

In [19]:
dt.fit(X_train, y_train)


DecisionTreeClassifier(random_state=1)

In [24]:
y_pred = dt.predict(X_test)
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [30]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [32]:
f1_score(y_test, y_pred)

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [33]:
from sklearn.metrics import accuracy_score

y_true = [0, 2, 1, 3]
y_pred = [0, 1, 2, 3]

# 일치하는 비율
print(accuracy_score(y_true, y_pred))

# 일치하는 개수
print(accuracy_score(y_true, y_pred, normalize = False))

0.5
2.0


In [34]:
from sklearn.metrics import confusion_matrix

y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]

# 대각 원소는 실제값과 예측값이 일치하는 경우
# 행과 열은 차례대로 0, 1, 2
# 행이 y_true
# 열이 y_pred
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]], dtype=int64)

In [45]:
# data frame 정의
df = pd.DataFrame([
    [42, 'male', 12,'reading','class2'],
    [35, 'U', 3,'cooking', 'class1'],
    [1000, 'female', 7,'cycling', 'class3'],
    [1000, 'U', 21,'U', 'class4']
])
df.columns=['age',
            'gender',
            'month_birth',
            'hobby','target']
print(df)

    age  gender  month_birth    hobby  target
0    42    male           12  reading  class2
1    35       U            3  cooking  class1
2  1000  female            7  cycling  class3
3  1000       U           21        U  class4


In [41]:
data_value = df['target'].values
data_value

array(['class2', 'class1', 'class3', 'class4'], dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder

In [38]:
class_label = LabelEncoder()
class_label

LabelEncoder()

In [42]:
y_new = class_label.fit_transform(data_value)
y_new

array([1, 0, 2, 3])

In [44]:
df['target'] = y_new
print(df)

    age  gender  month_birth    hobby  target
0    42    male           12  reading       1
1    35       U            3  cooking       0
2  1000  female            7  cycling       2
3  1000       U           21        U       3


In [46]:
y_ori = class_label.inverse_transform(y_new)
y_ori

array(['class2', 'class1', 'class3', 'class4'], dtype=object)

In [47]:
df['target'] = y_ori

In [48]:
print(df)

    age  gender  month_birth    hobby  target
0    42    male           12  reading  class2
1    35       U            3  cooking  class1
2  1000  female            7  cycling  class3
3  1000       U           21        U  class4


In [62]:
from sklearn.neighbors import KNeighborsClassifier as KNN

In [51]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [56]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [54]:
from sklearn.preprocessing import MinMaxScaler

In [55]:
scaler = MinMaxScaler()
scaler.fit(X)

MinMaxScaler()

In [57]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2)

In [60]:
X_te.shape

(30, 4)

In [64]:
knn = KNN(n_neighbors=5)

In [66]:
knn.fit(X_tr, y_tr)

KNeighborsClassifier()

In [71]:
y_pred = knn.predict(X_te)
len(y_pred)

30

In [70]:
len(y_te)

30

In [72]:
accuracy_score(y_te, y_pred)

1.0

In [73]:
confusion_matrix(y_te, y_pred)

array([[ 6,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 13]], dtype=int64)

In [74]:
# 데이터 불러오기
from sklearn import datasets

raw_wine = datasets.load_wine()

In [75]:
raw_wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [76]:
# feature, target
X = raw_wine.data
y = raw_wine.target

print(X.shape)
print(y.shape)

(178, 13)
(178,)


In [77]:
# 트레이닝 / 테스트 데이터 분할
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(133, 13)
(133,)
(45, 13)
(45,)


In [78]:
# 데이터 scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaling = scaler.transform(X_train)
X_test_scaling = scaler.transform(X_test)

In [79]:
from sklearn import svm

In [80]:
svm_model = svm.SVC(kernel='linear', random_state=0)

In [81]:
svm_model.fit(X_train_scaling, y_train)

SVC(kernel='linear', random_state=0)

In [85]:
y_pred =svm_model.predict(X_test_scaling)
y_pred 

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 2, 2,
       1, 2, 1, 2, 0, 2, 1, 0, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 1, 2, 2,
       0])

In [86]:
# 평가
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

# confusion matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9555555555555556
[[13  0  0]
 [ 0 19  1]
 [ 1  0 11]]


In [87]:
# 분류 리포트
from sklearn.metrics import classification_report

class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.95      0.97        20
           2       0.92      0.92      0.92        12

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [89]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue'],
    'Size': ['S', 'M', 'L', 'M', 'L'],
    'Price': [10, 20, 15, 10, 20]
})
print(df)

   Color Size  Price
0    Red    S     10
1   Blue    M     20
2  Green    L     15
3    Red    M     10
4   Blue    L     20


In [90]:
# y 정의
# dataframe 형태
y = df[['Size']]
type(y)

pandas.core.frame.DataFrame

In [92]:
print(y)

  Size
0    S
1    M
2    L
3    M
4    L


In [93]:
from sklearn.preprocessing import OneHotEncoder

In [94]:
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(y)

OneHotEncoder()

In [98]:
y_hot = onehot_encoder.transform(y)
y_hot

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [99]:
y_hot.toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [100]:
import numpy as np
X = np.array([['Korea', 44, 7200], 
['Japan', 27, 4800], 
['China', 30, 6100]])

In [107]:
XX = onehot_encoder.fit_transform(X[:,0].reshape(-1,1)).toarray()

In [ ]:
X[:,0].reshape(-1,1).

array([['Korea'],
       ['Japan'],
       ['China']], dtype='<U11')

In [108]:
X = np.delete(X, [0], axis=1)
X = np.concatenate((XX, X), axis =1)

In [120]:
onehot_color = pd.get_dummies(df['Color'], dtype=int)
print(onehot_color)

   Blue  Green  Red
0     0      0    1
1     1      0    0
2     0      1    0
3     0      0    1
4     1      0    0


    Blue  Green    Red
0  False  False   True
1   True  False  False
2  False   True  False
3  False  False   True
4   True  False  False


In [114]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue'],
    'Size': ['S', 'M', 'L', 'M', 'L'],
    'Price': [10, 20, 15, 10, 20]
})
print(df)

   Color Size  Price
0    Red    S     10
1   Blue    M     20
2  Green    L     15
3    Red    M     10
4   Blue    L     20


In [118]:
df_new = pd.concat([df, onehot_color], axis=1)
print(df_new)

   Color Size  Price   Blue  Green    Red
0    Red    S     10  False  False   True
1   Blue    M     20   True  False  False
2  Green    L     15  False   True  False
3    Red    M     10  False  False   True
4   Blue    L     20   True  False  False


In [121]:
onehot_color2 = pd.get_dummies(df['Color'], drop_first=True, dtype=int)
print(onehot_color2)

df_new2 = pd.concat([df, onehot_color2], axis=1)
print(df_new2)

   Green  Red
0      0    1
1      0    0
2      1    0
3      0    1
4      0    0
   Color Size  Price  Green  Red
0    Red    S     10      0    1
1   Blue    M     20      0    0
2  Green    L     15      1    0
3    Red    M     10      0    1
4   Blue    L     20      0    0


In [122]:
y

,Size
0,S
1,M
2,L
3,M
4,L


In [124]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
print(y_encoded)

[2 1 0 1 0]


c:\Programming\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [125]:
from tensorflow.keras.utils import to_categorical

In [126]:
y_hot2 = to_categorical(y_encoded)
y_hot2

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [127]:
class_vector =[2, 6, 6, 1]

output = to_categorical(class_vector, num_classes = 7)
print(output)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]]
