In [6]:
import numpy as np
from scipy.stats import norm

In [ ]:
# data
data = np.array([23, 25, 28, 30, 26, 27, 29, 32, 31, 28])

In [4]:
# 모집단의 평균과 분산 (표준편차)
population_mean = 28
population_variance = 4

# 유의수준 설정
alpha = 0.05

# 단측 또는 양측 검정 선택
alternative = 'two-sided'

# 표본평균 계산
sample_mean = np.mean(data)

# 표본 크기
n = len(data)

In [9]:
# 검정통계량 계산 (Z-검정)
test_statistic = (sample_mean - population_mean) / np.sqrt(population_variance/n)
print(test_statistic)

# 임계값 계산 (Z-검정, 양측 검정)
critical_value = norm.ppf(1 - alpha / 2)
print(critical_value)

# p-value 계산 (양측 검정)
p_value = 2 * (1 - norm.cdf(abs(test_statistic)))
print(p_value)

-0.15811388300842122
1.959963984540054
0.87436706116289


In [14]:
1- norm.cdf(abs(test_statistic))

0.437183530581445

In [10]:
# 결과
print('표본평균:', sample_mean)
print('검정통계량:', test_statistic)
print('임계값:', critical_value)
print('p-값:', p_value)

# 결과 해석
if abs(test_statistic) > critical_value:
    print('귀무가설 기각, 표본평균이 모집단 평균과 다름')
else:
    print('귀무가설 기각하지 못함, 표본평균과 모집단 평균과 차이가 없을 가능성 있음')

표본평균: 27.9
검정통계량: -0.15811388300842122
임계값: 1.959963984540054
p-값: 0.87436706116289
귀무가설 기각하지 못함, 표본평균과 모집단 평균과 차이가 없을 가능성 있음


In [11]:
norm.ppf(0.975)

1.959963984540054

In [12]:
norm.cdf(1.96)

0.9750021048517795

In [ ]:
# data
data = np.array([23, 25, 28, 30, 26, 27, 29, 32, 31, 28])

In [ ]:
# 유의수준 설정
alpha = 0.05

# 단측 또는 양측 검정 선택
alternative = 'two-sided'

In [26]:

from scipy import stats
# t-검정 수행
t_statistic, p_value = stats.ttest_1samp(data, popmean=0, alternative=alternative)

# 95% 신뢰구간 계산
confidence_interval = stats.t.interval(confidence=1-alpha, df=len(data) - 1, loc=np.mean(data), scale=stats.sem(data))

In [47]:
t_statistic, p_value = stats.ttest_1samp(data, popmean=0, alternative=alternative)

print(t_statistic, p_value)

31.887160448233363 1.4410218033665443e-10


In [27]:
# 결과
print('t-통계량:', t_statistic)
print('p-값:', p_value)
print('95% 신뢰구간:', confidence_interval)

# 결과 해석
if p_value < alpha:
    print('귀무가설 기각, 표본평균이 모집단 평균과 다름')
else:
    print('귀무가설 기각하지 못함, 표본평균과 모집단 평균과 차이가 없을 가능성 있음')

t-통계량: 31.887160448233363
p-값: 1.4410218033665443e-10
95% 신뢰구간: (25.920702252679696, 29.8792977473203)
귀무가설 기각, 표본평균이 모집단 평균과 다름


In [28]:
stats.sem(data)

0.8749603165604459

array([ 529,  625,  784,  900,  676,  729,  841, 1024,  961,  784])

In [30]:
xbar = np.mean(data)

In [41]:
s2 = np.sum((data - xbar)**2)/(len(data)-1)
s2

7.655555555555558

In [42]:
s = np.sqrt(s2)
s

2.7668674625929515

In [44]:
sem = s/np.sqrt(len(data))
sem

0.8749603165604459

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats

mtcars = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/mtcars.csv')


,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2


In [50]:
print(mtcars.head(5))

               model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  


In [52]:
# mpg 열의 표본평균 계산 및 반올림
mpg_mean = round(np.mean(mtcars['mpg']), 4)
print('mpg_mean:', mpg_mean)

mpg_mean: 20.0906


In [53]:
# mpg 열의 표본분산 계산 및 반올림
mpg_var = round(np.var(mtcars['mpg'], ddof=1), 4)
print('mpg_var:', mpg_var)

mpg_var: 36.3241


In [54]:
# 단일표본 t-검정 수행, mpg 열의 평균이 20인지 검정
t_stat, p_value = stats.ttest_1samp(mtcars['mpg'], popmean=20)
print('단일표본 t-검정 결과:')
print('t-통계량:', t_stat)
print('p-값:', p_value)


단일표본 t-검정 결과:
t-통계량: 0.08506003568133688
p-값: 0.9327606409093872


In [55]:
# mpg 평균의 95% 신뢰구간 계산 및 출력
conf_interval = stats.t.interval(confidence=0.95, df=len(mtcars['mpg'])-1, loc=np.mean(mtcars['mpg']), scale=stats.sem(mtcars['mpg']))

In [56]:
print('mpg 평균의 95% 신뢰구간:', round(conf_interval[0], 4), '-', round(conf_interval[1], 4))

mpg 평균의 95% 신뢰구간: 17.9177 - 22.2636


In [1]:
import scipy.stats as stats
import numpy as np

In [ ]:
# data
sample1 = [23, 25, 28, 30, 32]
sample2 = [19, 21, 24, 26, 29]

In [3]:
# t-검정 실행
t_statistic, p_value = stats.ttest_ind(sample1, sample2)

In [4]:
mean_sample1 = np.mean(sample1)
mean_sample2 = np.mean(sample2)

In [6]:
alpha = 0.05
print('t-검정통계량:', t_statistic)
print('Sample 1 평균:', mean_sample1)
print('Sample 2 평균:', mean_sample2)
print('p-값 (two-tailed):', p_value)
if p_value < alpha:
    print('두 그룹의 평균은 유의미하게 다름')
else:
    print('두 그룹의 평균은 유의미하게 다르지 않음')

t-검정통계량: 1.5778641172210597
Sample 1 평균: 27.6
Sample 2 평균: 23.8
p-값 (two-tailed): 0.15324889402868613
두 그룹의 평균은 유의미하게 다르지 않음


In [8]:
import scipy.stats as stats
import numpy as np

# data
sample1 = [23, 25, 28, 30, 32]
sample2 = [19, 21, 24, 26, 29]

# Mann-Whitney U 검정 실행
u_statistic, p_value = stats.mannwhitneyu(sample1, sample2)

# 각 샘플의 평균
mean_sample1 = np.mean(sample1)
mean_sample2 = np.mean(sample2)

# 결과
alpha = 0.05
print('Mann-Whitney U 통계량:', u_statistic)
print('Sample 1 평균:', mean_sample1)
print('Sample 2 평균:', mean_sample2)
print('p-값 (two-tailed):', p_value)

if p_value < alpha:
    print('두 그룹의 평균은 유의미하게 다름')
else:
    print('두 그룹의 평균은 유의미하게 다르지 않음')

Mann-Whitney U 통계량: 19.0
Sample 1 평균: 27.6
Sample 2 평균: 23.8
p-값 (two-tailed): 0.2222222222222222
두 그룹의 평균은 유의미하게 다르지 않음


In [9]:
from scipy import stats

# data
data = [2.4, 2.7, 3.1, 3.2, 3.5, 3.7, 3.9, 4.1, 4.2]

# Shapiro-Wilk 테스트
statistic, p_value = stats.shapiro(data)

# 결과
alpha = 0.05
print('Shapiro-Wilk 테스트 통계량:', statistic)
print('p-값 (two-tailed):', p_value)

if p_value < alpha:
    print('귀무가설 기각, 데이터는 정규분포를 따르지 않을 가능성 있음')
else:
    print('귀무가설 기각하지 못함. 데이터는 정규분포를 따를 가능성이 높음')

Shapiro-Wilk 테스트 통계량: 0.9553363445648536
p-값 (two-tailed): 0.7484769348718906
귀무가설 기각하지 못함. 데이터는 정규분포를 따를 가능성이 높음


In [12]:
# data
data_man = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
data_woman = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]

# 평균
mean_man = np.mean(data_man)
mean_woman = np.mean(data_woman)
print('남자 데이터 평균:', mean_man)
print('여자 데이터 평균:', mean_woman)

# Shapiro-Wilk 정규성 테스트
statistic_man, p_value_man = stats.shapiro(data_man)
statistic_woman, p_value_woman = stats.shapiro(data_woman)

# 결과
alpha = 0.05

print('남자 데이터 Shapiro-Wilk 테스트 통계량:', statistic_man)
print('남자 데이터 p-값 (two-tailed):', p_value_man)

if p_value_man < alpha:
    print('귀무가설 기각, 남자 데이터는 정규분포를 따르지 않을 가능성 있음')
else:
    print('귀무가설 기각하지 못함. 남자 데이터는 정규분포를 따를 가능성이 높음')

print('여자 데이터 Shapiro-Wilk 테스트 통계량:', statistic_woman)
print('여자 데이터 p-값 (two-tailed):', p_value_woman)

if p_value_woman < alpha:
    print('귀무가설 기각, 여자 데이터는 정규분포를 따르지 않을 가능성 있음')
else:
    print('귀무가설 기각하지 못함. 여자 데이터는 정규분포를 따를 가능성이 높음')

남자 데이터 평균: 100.0
여자 데이터 평균: 108.0
남자 데이터 Shapiro-Wilk 테스트 통계량: 0.9326357614973092
남자 데이터 p-값 (two-tailed): 0.17352612045868016
귀무가설 기각하지 못함. 남자 데이터는 정규분포를 따를 가능성이 높음
여자 데이터 Shapiro-Wilk 테스트 통계량: 0.9615265146509544
여자 데이터 p-값 (two-tailed): 0.5747781455168709
귀무가설 기각하지 못함. 여자 데이터는 정규분포를 따를 가능성이 높음


In [14]:
from scipy import stats

# 독립표본 t-검정
t_statistic, p_value = stats.ttest_ind(data_man, data_woman)

print('t-검정통계량:', t_statistic)
print('p-값:', p_value)

alpha = 0.05

if p_value < alpha:
    print('귀무가설 기각, 두 그룹의 평균은 유의미하게 다름')
else:
    print('귀무가설 기각 X, 두 그룹의 평균은 유의미하게 다르지 않음')

t-검정통계량: -2.670573872669349
p-값: 0.011082895240510138
귀무가설 기각, 두 그룹의 평균은 유의미하게 다름


In [15]:
from scipy import stats

data_before = [72, 75, 68, 71, 73]
data_after = [76, 79, 74, 78, 80]

t_statistic, p_value = stats.ttest_rel(data_before, data_after)

print('대응표본 t-검정 결과:')
print(f't-통계량 : {t_statistic}')
print(f'p-값 : {p_value}')

대응표본 t-검정 결과:
t-통계량 : -8.25674954467424
p-값 : 0.0011738040715128372


In [17]:
from scipy import stats

data_before = [7, 3, 4, 5, 2, 1, 6, 6, 5, 4]
data_after = [8, 4, 5, 6, 2, 3, 6, 8, 6, 5]

# Shapiro-Wilk 검정
_, p_value_before = stats.shapiro(data_before)
_, p_value_after = stats.shapiro(data_after)

# 결과
print('before 데이터의 정규성 검정:')
if p_value_before < 0.05:
    print('p-값:', p_value_before)
    print('before 데이터는 정규분포를 따르지 않는다.')
else:
    print('p-값:', p_value_before)
    print('before 데이터는 정규분포를 따른다.')

print('after 데이터의 정규성 검정:')
if p_value_after < 0.05:
    print('p-값:', p_value_after)
    print('after 데이터는 정규분포를 따르지 않는다.')
else:
    print('p-값:', p_value_after)
    print('after 데이터는 정규분포를 따른다.')


before 데이터의 정규성 검정:
p-값: 0.8352703969642297
before 데이터는 정규분포를 따른다.
after 데이터의 정규성 검정:
p-값: 0.6177986322207938
after 데이터는 정규분포를 따른다.


In [ ]:

t_statistic, p_value = stats.ttest_rel(data_before, data_after)

print('대응표본 t-검정 결과:')
print(f't-통계량 : {t_statistic}')
print(f'p-값 : {p_value}')

In [19]:
import numpy as np
from scipy import stats

data_before = np.array([7, 3, 4, 5, 2, 1, 6, 6, 5, 4])
data_after = np.array([8, 4, 5, 6, 2, 3, 6, 8, 6, 5])

# 차이 값 계산
D = data_before - data_after

# 대응표본 t-검정 수행
t_statistic, p_value = stats.ttest_rel(data_before, data_after)

print('대응표본 t-검정 결과:')
print(f't-통계량 : {t_statistic}')
print(f'p-값 : {p_value}')

# 가설 검정
alpha = 0.05 # 유의수준

if p_value < alpha:
    print('p-값이 유의수준보다 작으므로 귀무가설 기각.')
else:
    print('p-값이 유의수준보다 크므로 귀무가설 기각하지 않음.')

대응표본 t-검정 결과:
t-통계량 : -4.743416490252569
p-값 : 0.0010538712570165528
p-값이 유의수준보다 작으므로 귀무가설 기각.


In [20]:
import numpy as np
from scipy import stats

# data
data = np.array([14.2, 15.1, 14.8, 15.4, 14.9, 15.2, 14.6, 15.0])

# 가설 설정
# H0 : 모분산은 1.0과 같다.
# H1 : 모분산은 1.0과 다르다.

population_variance = 1.0 # 모분산

# 검정통계량 = (n-1) * 표본분산 / 모분산
sample_variance = np.var(data, ddof=1)
n = len(data)
chi2_stat = (n-1) * sample_variance / population_variance

# 카이제곱 분포의 자유도
degrees_of_freedom = n-1

# p-값 계산
p_value = 1 - stats.chi2.cdf(chi2_stat, degrees_of_freedom)

# 결과
print('Chi-Square Statistic:', chi2_stat)
print('p-value:', p_value)

# 유의수준 0.05로 가설 검정
alpha = 0.05
if p_value < alpha:
    print('귀무가설 기각. 모분산은 1.0과 다름')
else:
    print('귀무가설 기각 X. 모분산은 1.0과 같을 가능성 있음.')

Chi-Square Statistic: 0.9800000000000009
p-value: 0.9951447440742881
귀무가설 기각 X. 모분산은 1.0과 같을 가능성 있음.


In [ ]:
import numpy as np
np.random.seed(123)

# data 생성
sample1 = np.random.normal(loc=5, scale=2, size=50)
sample2 = np.random.normal(loc=5, scale=3, size=50)
print(sample1)
print(sample2)

[ 2.82873879  6.99469089  5.565957    1.98741057  3.8427995   8.30287307
  0.14664151  4.14217474  7.53187252  3.2665192   3.6422277   4.81058206
  7.98277925  3.72219601  4.11203608  4.13129745  9.41186017  9.37357218
  7.0081078   5.7723728   6.47473715  7.98146406  3.12833226  7.35165809
  2.49223866  3.724497    6.81421039  2.1426386   4.71986256  3.27649021
  4.48876126 -0.59717821  1.45693379  3.60024553  6.85492486  4.65272863
  5.00569183  6.37644542  3.24092731  5.56725465  3.38926696  1.54466101
  4.21820041  6.14761172  5.6771781   4.97633901  9.78473053  5.82582432
  6.95747201  9.47628668]
[ 1.11774403  1.88363537 10.23113668  2.60581179  5.08904969  8.20794791
  7.67211917 10.26465855  9.48693241  8.20817801  2.68187386  7.384588
  5.94281598  1.02120362  9.25189714  7.4217096   5.13647024  4.30072382
  1.40509657  5.59857222  6.40531736  2.50653505  8.48661215  1.70839086
 -1.36930105  8.11918127  3.78990189  4.62191124  2.48744983  0.18211172
  8.76571212  2.93339305  9

In [22]:
from scipy import stats

# 두 표본의 분산 계산
variance_sample1 = np.var(sample1, ddof=1)
variance_sample2 = np.var(sample2, ddof=1)

# F-검정
f_statistic = variance_sample1 / variance_sample2
df1 = len(sample1) - 1
df2 = len(sample2) - 1
p_value = 1 - stats.f.cdf(f_statistic, df1, df2)

print(f'표본 1의 분산: {variance_sample1:.4f}')
print(f'표본 2의 분산: {variance_sample2:.4f}')
print(f'F-통계량: {f_statistic:.4f}')

alpha = 0.05
if p_value < alpha:
    print(f'p-value: {p_value:.4f} < {alpha}, 귀무가설 기각. 두 표본의 분산은 다름.')
else:
    print(f'p-value: {p_value:.4f} >= {alpha}, 귀무가설 기각 X. 두 표본의 분산은 같을 수 있음.')


표본 1의 분산: 5.7763
표본 2의 분산: 10.3800
F-통계량: 0.5565
p-value: 0.9787 >= 0.05, 귀무가설 기각 X. 두 표본의 분산은 같을 수 있음.


In [23]:
import numpy as np
from scipy import stats

# data
data_matrix = np.array([[50, 75, 125, 175],
                        [90, 30, 45, 10]])

# 카이제곱 독립성 검정
chi2, p, df, expected = stats.chi2_contingency(data_matrix)

# 결과
print('Chi-square statistic:', chi2)
print('p-value:', p)
print('Degrees of freedom:', df)
print('Expected frequencies table:')
print(expected)

Chi-square statistic: 134.7511341579557
p-value: 5.117490956087995e-29
Degrees of freedom: 3
Expected frequencies table:
[[ 99.16666667  74.375      120.41666667 131.04166667]
 [ 40.83333333  30.625       49.58333333  53.95833333]]


In [28]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

# 타이타닉 데이터셋
titanic_data = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/titanic.csv')
print(titanic_data.head(5))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [27]:
# 교차표 생성: 성별(Sex)과 생존 여부(Survived)를 기반
cross_table = pd.crosstab(titanic_data['Sex'], titanic_data['Survived'])
print(cross_table)

# 카이제곱 독립성 검정
chi2, p, df, expected = chi2_contingency(cross_table)

# 결과
print('카이제곱 통계량:', chi2)
print('p-value:', p)
print('자유도(df)', df)
print('기대값(Expected Frequencies)')
print(expected)

Survived    0    1
Sex               
female     81  233
male      468  109
카이제곱 통계량: 260.71702016732104
p-value: 1.1973570627755645e-58
자유도(df) 1
기대값(Expected Frequencies)
[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]


In [29]:
# 나이를 그룹으로 나누는 함수 정의
def categorize_age(age):
    if age < 20:
        return '10대'
    elif age < 30:
        return '20대'
    elif age < 40:
        return '30대'
    elif age < 50:
        return '40대'
    elif age < 60:
        return '50대'
    else:
        return '60대 이상'

# 나이가 NaN인 경우 해당 열의 평균값으로 대체
average_age = titanic_data['Age'].mean()
titanic_data['Age'] = titanic_data['Age'].apply(lambda x: average_age if np.isnan(x) else x)

# apply() 함수로 새로운 열 생성
titanic_data['AgeGroup'] = titanic_data['Age'].apply(categorize_age)

# 결과
print(titanic_data[['Age', 'AgeGroup']])

           Age AgeGroup
0    22.000000      20대
1    38.000000      30대
2    26.000000      20대
3    35.000000      30대
4    35.000000      30대
..         ...      ...
886  27.000000      20대
887  19.000000      10대
888  29.699118      20대
889  26.000000      20대
890  32.000000      30대

[891 rows x 2 columns]


In [30]:
# 교차표 생성: 연령대(AgeGroup)와 생존 여부(Survived)를 기반
cross_table = pd.crosstab(titanic_data['AgeGroup'], titanic_data['Survived'])

# 카이제곱 독립성 검정
chi2, p, df, expected = chi2_contingency(cross_table)

# 결과
print('카이제곱 통계량:', chi2)
print('p-value:', p)
print('자유도(df)', df)
print('기대값(Expected Frequencies)')
print(expected)

카이제곱 통계량: 16.134525241016338
p-value: 0.006470311249228111
자유도(df) 5
기대값(Expected Frequencies)
[[101.05050505  62.94949495]
 [244.61616162 152.38383838]
 [102.8989899   64.1010101 ]
 [ 54.83838384  34.16161616]
 [ 29.57575758  18.42424242]
 [ 16.02020202   9.97979798]]
