In [38]:
import numpy as np
import scipy.stats as stats

In [18]:
# euclidean
u1 = np.array([4, 1, 1, 4])
u3 = np.array([2, 0, 4,5 ])

euc_sim = np.sqrt(np.sum((u1 - u3)**2))
euc_sim

3.872983346207417

In [ ]:
# Mean squared Difference (MSD)
# euclidean에서 null 값을 제거한 것들끼리의 유사도

u1 = np.array([4, 1, 1, 4])
u3 = np.array([2, 0, 4, 5])

MSD = (2**2+ 3**2+ 1**2)/3
MSD

4.666666666666667

In [53]:
# JMSD
u1 = np.array([4, 1, 1, 4])
u1_norm = u1/5

u3 = np.array([2, 0, 4, 5])
u3_norm = u3/5

jcd = 3/4
MSD = ((u1_norm[0] - u3_norm[0])**2 + (u1_norm[2] - u3_norm[2])**2 + (u1_norm[3] - u3_norm[3])**2)/3

JMSD = jcd * (1-MSD)
JMSD

0.61

In [37]:
# cosine
u1 = np.array([5, 4, 3])
u3 = np.array([3, 5, 4])

# cos_sim = np.sum((u1 * u3))/(np.sqrt(np.sum(u1**2)) * np.sqrt(np.sum((u3**2))))
cos_sim = np.sum((u1 * u3))/(np.linalg.norm(u1, ord = 2) * np.linalg.norm(u3, ord = 2))

cos_sim

0.9399999999999998

In [64]:
# pearson correlation coefficient (PCC)
u1 = np.array([4, 1, 1, 4])
u3 = np.array([2,    4, 5])

u1_mean = np.mean(u1)
u3_mean = np.mean(u3)

new_u1 = np.array([4, 1, 4])
new_u3 = np.array([2, 4, 5])

a = new_u1-u1_mean
b = new_u3-u3_mean

pcc = np.sum(a*b) / (np.linalg.norm(a) * np.linalg.norm(b))
pcc

-0.17817416127494962

In [63]:
# Constrained Pearson
u1 = np.array([4, 1, 1, 4])
u3 = np.array([2,    4, 5])

u1_med = np.median(u1)
u3_med = np.median(u3)

new_u1 = np.array([4, 1, 4])
new_u3 = np.array([2, 4, 5])

a = new_u1-u1_med
b = new_u3-u3_med

pcc = np.sum(a*b) / (np.linalg.norm(a) * np.linalg.norm(b))
pcc

-0.2581988897471611

# Predicting rating

In [1]:
import torch
import numpy as np
import torch.nn as nn

In [11]:
a = torch.randn(5,5)
print(a)
print(torch.sigmoid(a))

b=torch.softmax(a, dim=-1)
print(b)


tensor([[ 1.6803, -0.4092, -0.4208,  2.5337, -0.5688],
        [-0.5046, -0.2327,  0.1694,  1.2958,  0.0040],
        [-0.6674,  0.5148,  0.2724,  0.7052,  0.2956],
        [-0.4160, -0.8628, -0.3162,  0.2292, -0.2077],
        [ 0.3218, -0.4759,  1.9482, -0.6812,  0.3304]])
tensor([[0.8429, 0.3991, 0.3963, 0.9265, 0.3615],
        [0.3765, 0.4421, 0.5422, 0.7851, 0.5010],
        [0.3391, 0.6259, 0.5677, 0.6693, 0.5734],
        [0.3975, 0.2967, 0.4216, 0.5570, 0.4483],
        [0.5798, 0.3832, 0.8753, 0.3360, 0.5819]])
tensor([[0.2703, 0.0335, 0.0331, 0.6346, 0.0285],
        [0.0834, 0.1095, 0.1636, 0.5048, 0.1387],
        [0.0747, 0.2436, 0.1912, 0.2947, 0.1957],
        [0.1700, 0.1087, 0.1878, 0.3241, 0.2094],
        [0.1264, 0.0569, 0.6428, 0.0464, 0.1275]])


In [17]:
a = [0.0425, 0.0349, 0.0409, 0.0401, 0.0512, 0.0434, 0.0353, 0.0382, 0.0407,
         0.0641, 0.0427, 0.0420, 0.0449, 0.0415, 0.0452, 0.0444, 0.0425, 0.0410,
         0.0445, 0.0419, 0.0377, 0.0578, 0.0425]
np.sum(a)

0.9998999999999999

In [ ]:
# L1 norm
# 정규화하면 항상 상수
np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# 각 헤드 attention map 합
A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# normalization
A_tilde = A / A_sum # (H, N, T)

# 각 헤드 L_sparse
L_sparse_h = np.sum(np.abs(A_tilde), axis=(1,2)) # (H, )
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

L_sparse_h: [1. 1. 1. 1.]
L_sparse: 1.0


In [ ]:
# L1 norm
# 정규화안하면? 너무 큼;
np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# # 각 헤드 attention map 합
# A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# # normalization
# A_tilde = A / A_sum # (H, N, T)

# 각 헤드 L_sparse
L_sparse_h = np.sum(np.abs(A), axis=(1,2)) # (H, )
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

L_sparse_h: [751.61065834 761.10900491 730.89206559 734.63562859]
L_sparse: 744.5618393542486


In [ ]:
# L2 norm
# 클수록 sparse? 따라서 loss는 마이너스
np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# 각 헤드 attention map 합
A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# normalization
A_tilde = A / A_sum # (H, N, T)

# 각 헤드 L_sparse
L_sparse_h = np.sqrt(np.sum(A_tilde**2, axis=(1,2))) # (H, )
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

L_sparse_h: [0.02994695 0.02973857 0.02990276 0.02994167]
L_sparse: 0.02988248741742505


In [30]:
np.sum(A_tilde**2, axis=(1,2))

array([0.00089682, 0.00088438, 0.00089418, 0.0008965 ])

In [8]:
L_sparse_h

array([-0.00089682, -0.00088438, -0.00089418, -0.0008965 ])

In [91]:

class MultiHeadSparsityLoss(nn.Module):
    """
    Implements the multi-head sparsity regularization:
        For each head h, A^{(h)} ∈ R^{N×T} is normalized by its sum,
        then L_sparse^{(h)} = ||Â^{(h)}||_1, and
        L_sparse = (1/H) * sum_h L_sparse^{(h)}.
    Supports input shapes (B,H,N,T) or (B,N,T). Optionally supports a mask over frames.
    """
    def __init__(self, eps: float = 1e-12, reduction: str = "mean"):
        """
        eps: small constant to avoid division by zero
        reduction: 'mean' (default), 'sum', or 'none' over the batch
        """
        super().__init__()
        self.eps = eps
        assert reduction in ("mean", "sum", "none")
        self.reduction = reduction

    def forward(self, A: torch.Tensor, frame_mask: torch.Tensor = None) -> torch.Tensor:
        """
        Args
        ----
        A : torch.Tensor
            Attention maps with shape (B,H,N,T) or (B,N,T).
        frame_mask : torch.Tensor, optional
            Valid-frame mask of shape (B,T) or (B,1,T). Ones for valid frames, zeros for padded frames.

        Returns
        -------
        loss : torch.Tensor
            Scalar loss if reduction != 'none', else (B,) vector.
        """
        if A.ndim == 3:
            # (B,N,T) -> add H=1
            A = A.unsqueeze(1)  # (B,1,N,T)
        elif A.ndim != 4:
            raise ValueError("A must be (B,H,N,T) or (B,N,T).")

        B, H, N, T = A.shape

        # Optionally apply frame mask before normalization (mask invalid frames to zero)
        if frame_mask is not None:
            if frame_mask.ndim == 2:
                frame_mask = frame_mask.unsqueeze(1)  # (B,1,T)
            if frame_mask.ndim == 3:
                # Broadcast to (B,1,1,T)
                frame_mask = frame_mask.unsqueeze(1) if frame_mask.shape[1] != 1 else frame_mask
            # reshape to (B,1,1,T) for broadcast over heads and joints
            frame_mask = frame_mask.view(B, 1, 1, T)
            A = A * frame_mask  # zero-out invalid frames

        # Head-wise normalization by total sum over (N,T) so that sum_i,t Â^{(h)}_{i,t} = 1
        sums = A.sum(dim=(2, 3), keepdim=True).clamp_min(self.eps)  # (B,H,1,1)
        A_tilde = A / sums  # (B,H,N,T)

        # L1 per head: ||Â^{(h)}||_1 = sum_{i,t} |Â^{(h)}_{i,t}|
        # A_tilde >= 0 assumed (attention weights). If not guaranteed, abs() is safe.
        L_sparse_h = A_tilde.abs().sum(dim=(2, 3))  # (B,H)

        # L_sparse_h = -torch.sqrt(torch.sum(A_tilde ** 2, dim = (2,3))) + self.eps
        # L_sparse_h = -torch.sum(A_tilde ** 2, dim = (2,3))

        # # 여기만;;
        # # L1 per head: ||Â^{(h)}||_1 = sum_{i,t} |Â^{(h)}_{i,t}|
        # # A_tilde >= 0 assumed (attention weights). If not guaranteed, abs() is safe.
        # L_sparse_h = A.abs().sum(dim=(2, 3))  # (B,H)

 

        # Average over heads: (1/H) * sum_h L_sparse^{(h)}
        L_sparse = L_sparse_h.mean(dim=1)  # (B,)

        if self.reduction == "mean":
            return L_sparse.mean()
        elif self.reduction == "sum":
            return L_sparse.sum()
        else:  # 'none'
            return L_sparse  # (B,)


# ---------------------------
# 사용 예시
# ---------------------------
if __name__ == "__main__":
    B, H, N, T = 8, 4, 25, 48
    A = torch.rand(B, H, N, T, requires_grad=True)  # 예시 attention
    y = torch.randint(0, 300, (B,))                 # 예시 라벨
    logits = torch.randn(B, 300, requires_grad=True)

    # 손실들
    ce = nn.CrossEntropyLoss()(logits, y)

    sparse_loss_fn = MultiHeadSparsityLoss(eps=1e-12, reduction="mean")
    L_sparse = sparse_loss_fn(A)  # \mathcal{L}_{sparse}

    # 가중합 (예: lambda_s = 0.1)
    lambda_s = 0.1
    loss = ce + lambda_s * L_sparse
    loss.backward()

    print('L_sparse:', L_sparse)
    print(f"L_sparse={L_sparse.item():.12f}")

    print(loss)

L_sparse: tensor(1., grad_fn=<MeanBackward0>)
L_sparse=1.000000000000
tensor(5.9592, grad_fn=<AddBackward0>)
