In [38]:
import numpy as np
import scipy.stats as stats

In [18]:
# euclidean
u1 = np.array([4, 1, 1, 4])
u3 = np.array([2, 0, 4,5 ])

euc_sim = np.sqrt(np.sum((u1 - u3)**2))
euc_sim

3.872983346207417

In [ ]:
# Mean squared Difference (MSD)
# euclidean에서 null 값을 제거한 것들끼리의 유사도

u1 = np.array([4, 1, 1, 4])
u3 = np.array([2, 0, 4, 5])

MSD = (2**2+ 3**2+ 1**2)/3
MSD

4.666666666666667

In [53]:
# JMSD
u1 = np.array([4, 1, 1, 4])
u1_norm = u1/5

u3 = np.array([2, 0, 4, 5])
u3_norm = u3/5

jcd = 3/4
MSD = ((u1_norm[0] - u3_norm[0])**2 + (u1_norm[2] - u3_norm[2])**2 + (u1_norm[3] - u3_norm[3])**2)/3

JMSD = jcd * (1-MSD)
JMSD

0.61

In [37]:
# cosine
u1 = np.array([5, 4, 3])
u3 = np.array([3, 5, 4])

# cos_sim = np.sum((u1 * u3))/(np.sqrt(np.sum(u1**2)) * np.sqrt(np.sum((u3**2))))
cos_sim = np.sum((u1 * u3))/(np.linalg.norm(u1, ord = 2) * np.linalg.norm(u3, ord = 2))

cos_sim

0.9399999999999998

In [64]:
# pearson correlation coefficient (PCC)
u1 = np.array([4, 1, 1, 4])
u3 = np.array([2,    4, 5])

u1_mean = np.mean(u1)
u3_mean = np.mean(u3)

new_u1 = np.array([4, 1, 4])
new_u3 = np.array([2, 4, 5])

a = new_u1-u1_mean
b = new_u3-u3_mean

pcc = np.sum(a*b) / (np.linalg.norm(a) * np.linalg.norm(b))
pcc

-0.17817416127494962

In [63]:
# Constrained Pearson
u1 = np.array([4, 1, 1, 4])
u3 = np.array([2,    4, 5])

u1_med = np.median(u1)
u3_med = np.median(u3)

new_u1 = np.array([4, 1, 4])
new_u3 = np.array([2, 4, 5])

a = new_u1-u1_med
b = new_u3-u3_med

pcc = np.sum(a*b) / (np.linalg.norm(a) * np.linalg.norm(b))
pcc

-0.2581988897471611

# Predicting rating

In [1]:
import torch
import numpy as np
import torch.nn as nn

In [11]:
a = torch.randn(5,5)
print(a)
print(torch.sigmoid(a))

b=torch.softmax(a, dim=-1)
print(b)


tensor([[ 1.6803, -0.4092, -0.4208,  2.5337, -0.5688],
        [-0.5046, -0.2327,  0.1694,  1.2958,  0.0040],
        [-0.6674,  0.5148,  0.2724,  0.7052,  0.2956],
        [-0.4160, -0.8628, -0.3162,  0.2292, -0.2077],
        [ 0.3218, -0.4759,  1.9482, -0.6812,  0.3304]])
tensor([[0.8429, 0.3991, 0.3963, 0.9265, 0.3615],
        [0.3765, 0.4421, 0.5422, 0.7851, 0.5010],
        [0.3391, 0.6259, 0.5677, 0.6693, 0.5734],
        [0.3975, 0.2967, 0.4216, 0.5570, 0.4483],
        [0.5798, 0.3832, 0.8753, 0.3360, 0.5819]])
tensor([[0.2703, 0.0335, 0.0331, 0.6346, 0.0285],
        [0.0834, 0.1095, 0.1636, 0.5048, 0.1387],
        [0.0747, 0.2436, 0.1912, 0.2947, 0.1957],
        [0.1700, 0.1087, 0.1878, 0.3241, 0.2094],
        [0.1264, 0.0569, 0.6428, 0.0464, 0.1275]])


In [17]:
a = [0.0425, 0.0349, 0.0409, 0.0401, 0.0512, 0.0434, 0.0353, 0.0382, 0.0407,
         0.0641, 0.0427, 0.0420, 0.0449, 0.0415, 0.0452, 0.0444, 0.0425, 0.0410,
         0.0445, 0.0419, 0.0377, 0.0578, 0.0425]
np.sum(a)

0.9998999999999999

In [19]:
# L1 norm
# 정규화하면 항상 상수
# np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# 각 헤드 attention map 합
A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# normalization
A_tilde = A / A_sum # (H, N, T)

# 각 헤드 L_sparse
L_sparse_h = np.sum(np.abs(A_tilde), axis=(1,2)) # (H, )
print(np.abs(A_tilde))
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

[[[9.96086014e-04 1.40002958e-04 6.53129869e-05 ... 8.67607086e-04
   1.89510673e-05 7.77334808e-04]
  [1.20792449e-03 1.24203174e-03 1.37730703e-04 ... 1.16115137e-03
   3.22658977e-04 1.23653129e-03]
  [1.27422929e-03 2.95993543e-05 2.19334323e-04 ... 4.96792581e-05
   2.39761530e-05 1.38970771e-04]
  [5.02671928e-04 8.09809775e-04 2.86705408e-04 ... 8.37966111e-04
   3.90332985e-04 1.20886060e-03]
  [5.81566608e-04 1.23801236e-03 8.63581442e-04 ... 8.87684332e-04
   6.28903503e-04 6.43869022e-04]]

 [[8.14144972e-04 6.70689662e-04 1.80271645e-04 ... 2.23350775e-04
   6.10940092e-04 4.99922657e-04]
  [9.05418413e-04 2.34268882e-04 1.32305265e-03 ... 8.53180921e-04
   1.04459944e-03 2.07302534e-04]
  [5.98402304e-04 8.72521888e-04 5.05045961e-04 ... 7.84226175e-04
   1.78361746e-04 3.75681459e-04]
  [1.28040257e-03 1.16917109e-03 6.62470770e-05 ... 2.37887255e-04
   1.14842629e-03 1.31609026e-03]
  [3.80767470e-04 1.10537499e-03 7.38960107e-04 ... 3.73055239e-04
   8.82357814e-04 6.50

In [ ]:
# L1 norm
# 정규화안하면? 너무 큼;
np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# # 각 헤드 attention map 합
# A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# # normalization
# A_tilde = A / A_sum # (H, N, T)

# 각 헤드 L_sparse
L_sparse_h = np.sum(np.abs(A), axis=(1,2)) # (H, )
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

L_sparse_h: [751.61065834 761.10900491 730.89206559 734.63562859]
L_sparse: 744.5618393542486


In [ ]:
# L2 norm
# 클수록 sparse? 따라서 loss는 마이너스
np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# 각 헤드 attention map 합
A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# normalization
A_tilde = A / A_sum # (H, N, T)

# 각 헤드 L_sparse
L_sparse_h = np.sqrt(np.sum(A_tilde**2, axis=(1,2))) # (H, )
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

L_sparse_h: [0.02994695 0.02973857 0.02990276 0.02994167]
L_sparse: 0.02988248741742505


In [38]:
# entropy
# np.random.seed(0)

# attention map
H, N, T = 4, 5, 300
A = np.random.rand(H, N, T)

# 각 헤드 attention map 합
A_sum = A.sum(axis=(1,2), keepdims=True) # (H, 1, 1)

# normalization
A_tilde = A / A_sum # (H, N, T)

# entropy
eps = 1e-12
ent_h = -np.sum(A_tilde * np.log(A_tilde+eps), axis=(1,2))

# 각 헤드 L_sparse
L_sparse_h = ent_h
print('L_sparse_h:', L_sparse_h)

# L_sparse
L_sparse = np.sum(L_sparse_h) / H
print('L_sparse:', L_sparse)

L_sparse_h: [7.11137899 7.13174637 7.1210385  7.11569716]
L_sparse: 7.119965256725331


TypeError: log(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [8]:
L_sparse_h

array([-0.00089682, -0.00088438, -0.00089418, -0.0008965 ])

In [43]:

class MultiHeadSparsityLoss(nn.Module):
    """
    Implements the multi-head sparsity regularization:
        For each head h, A^{(h)} ∈ R^{N×T} is normalized by its sum,
        then L_sparse^{(h)} = ||Â^{(h)}||_1, and
        L_sparse = (1/H) * sum_h L_sparse^{(h)}.
    Supports input shapes (B,H,N,T) or (B,N,T). Optionally supports a mask over frames.
    """
    def __init__(self, eps: float = 1e-12, reduction: str = "mean"):
        """
        eps: small constant to avoid division by zero
        reduction: 'mean' (default), 'sum', or 'none' over the batch
        """
        super().__init__()
        self.eps = eps
        assert reduction in ("mean", "sum", "none")
        self.reduction = reduction

    def forward(self, A: torch.Tensor, frame_mask: torch.Tensor = None) -> torch.Tensor:
        """
        Args
        ----
        A : torch.Tensor
            Attention maps with shape (B,H,N,T) or (B,N,T).
        frame_mask : torch.Tensor, optional
            Valid-frame mask of shape (B,T) or (B,1,T). Ones for valid frames, zeros for padded frames.

        Returns
        -------
        loss : torch.Tensor
            Scalar loss if reduction != 'none', else (B,) vector.
        """
        if A.ndim == 3:
            # (B,N,T) -> add H=1
            A = A.unsqueeze(1)  # (B,1,N,T)
        elif A.ndim != 4:
            raise ValueError("A must be (B,H,N,T) or (B,N,T).")

        B, H, N, T = A.shape

        # Optionally apply frame mask before normalization (mask invalid frames to zero)
        if frame_mask is not None:
            if frame_mask.ndim == 2:
                frame_mask = frame_mask.unsqueeze(1)  # (B,1,T)
            if frame_mask.ndim == 3:
                # Broadcast to (B,1,1,T)
                frame_mask = frame_mask.unsqueeze(1) if frame_mask.shape[1] != 1 else frame_mask
            # reshape to (B,1,1,T) for broadcast over heads and joints
            frame_mask = frame_mask.view(B, 1, 1, T)
            A = A * frame_mask  # zero-out invalid frames

        # Head-wise normalization by total sum over (N,T) so that sum_i,t Â^{(h)}_{i,t} = 1
        sums = A.sum(dim=(2, 3), keepdim=True).clamp_min(self.eps)  # (B,H,1,1)
        A_tilde = A / sums  # (B,H,N,T)

        # L1 per head: ||Â^{(h)}||_1 = sum_{i,t} |Â^{(h)}_{i,t}|
        # A_tilde >= 0 assumed (attention weights). If not guaranteed, abs() is safe.
        # L_sparse_h = A_tilde.abs().sum(dim=(2, 3))  # (B,H)

        # L_sparse_h = -torch.sqrt(torch.sum(A_tilde ** 2, dim = (2,3))) + self.eps
        # L_sparse_h = -torch.sum(A_tilde ** 2, dim = (2,3))

        # # 여기만;;
        # # L1 per head: ||Â^{(h)}||_1 = sum_{i,t} |Â^{(h)}_{i,t}|
        # # A_tilde >= 0 assumed (attention weights). If not guaranteed, abs() is safe.
        # L_sparse_h = A.abs().sum(dim=(2, 3))  # (B,H)

        ent_h = -torch.sum(A_tilde * torch.log(A_tilde+eps), dim=(-1,-2))
        ent_h
        L_sparse_h = ent_h
        print('L_sparse_h:', L_sparse_h)
        # Average over heads: (1/H) * sum_h L_sparse^{(h)}
        L_sparse = L_sparse_h.mean(dim=1)  # (B,)

        if self.reduction == "mean":
            return L_sparse.mean()
        elif self.reduction == "sum":
            return L_sparse.sum()
        else:  # 'none'
            return L_sparse  # (B,)


# ---------------------------
# 사용 예시
# ---------------------------
if __name__ == "__main__":
    B, H, N, T = 8, 4, 25, 48
    A = torch.rand(B, H, N, T, requires_grad=True)  # 예시 attention
    y = torch.randint(0, 300, (B,))                 # 예시 라벨
    logits = torch.randn(B, 300, requires_grad=True)

    # 손실들
    ce = nn.CrossEntropyLoss()(logits, y)

    sparse_loss_fn = MultiHeadSparsityLoss(eps=1e-12, reduction="mean")
    L_sparse = sparse_loss_fn(A)  # \mathcal{L}_{sparse}

    # 가중합 (예: lambda_s = 0.1)
    lambda_s = 0.1
    loss = ce + lambda_s * L_sparse
    loss.backward()

    print('L_sparse:', L_sparse)
    print(f"L_sparse={L_sparse.item():.12f}")

    print(loss)

L_sparse_h: tensor([[6.9057, 6.8923, 6.8965, 6.9063],
        [6.8951, 6.9125, 6.9044, 6.9081],
        [6.8915, 6.8820, 6.8944, 6.8934],
        [6.8963, 6.9046, 6.9045, 6.8902],
        [6.9051, 6.9067, 6.8933, 6.9208],
        [6.9002, 6.9028, 6.8940, 6.8972],
        [6.8902, 6.9010, 6.8886, 6.9130],
        [6.8912, 6.8819, 6.8911, 6.8909]], grad_fn=<NegBackward0>)
L_sparse: tensor(6.8983, grad_fn=<MeanBackward0>)
L_sparse=6.898311614990
tensor(6.6281, grad_fn=<AddBackward0>)


In [2]:
nn.Identity()

Identity()

In [3]:
import dgl
import torch

c:\Programming\Anaconda\envs\chem2\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
def foo(g):
    with g.local_scope():
        g.edata['h'] = torch.ones((g.num_edges(), 3))
        g.edata['h2'] = torch.ones((g.num_edges(), 3))
        return g.edata['h']
g = dgl.graph((torch.tensor([0, 1, 1]), torch.tensor([0, 0, 2])))
g.edata['h'] = torch.zeros((g.num_edges(), 3))
newh = foo(g)
print(g.edata['h'])  # still get tensor of all zeros
'h2' in g.edata      # new feature set in the function scope is not found

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


False

In [9]:
def foo(g):
    with g.local_scope():
        # in-place operation
        g.edata['h'] += 1
        return g.edata['h']
g = dgl.graph((torch.tensor([0, 1, 1]), torch.tensor([0, 0, 2])))
g.edata['h'] = torch.zeros((g.num_edges(), 1))
newh = foo(g)
print(g.edata['h'])  # the result changes

tensor([[1.],
        [1.],
        [1.]])


In [14]:
g = dgl.graph((torch.tensor([0, 1, 1]), torch.tensor([0, 0, 2])))
g.num_edges()

3

In [17]:
g.edata['h'] = torch.ones((4, 5))
g

DGLError: Expect number of features to match number of edges. Got 4 and 3 instead.

In [30]:
src = torch.tensor([0, 0, 1, 2])  # 0->1, 0->2, 1->0, 2->0
dst = torch.tensor([1, 2, 0, 0])
g = dgl.graph((src, dst), num_nodes=3)
g.num_edges()

4

In [31]:
# self loop 추가
g = dgl.add_self_loop(g)


In [33]:
print("num_nodes:", g.num_nodes())
print("num_edges:", g.num_edges())
print("edges (src->dst):", g.edges())

num_nodes: 3
num_edges: 7
edges (src->dst): (tensor([0, 0, 1, 2, 0, 1, 2]), tensor([1, 2, 0, 0, 0, 1, 2]))


In [34]:
# node feature
x = torch.tensor([
    [0., 1.],  # node 0 = O
    [1., 0.],  # node 1 = H
    [1., 0.],  # node 2 = H
])

In [ ]:
import torch
import torch.nn as nn
import dgl
import dgl.function as fn

# -------------------------
# Your modules 그대로
# -------------------------
class NodeApplyModule(nn.Module):
    def __init__(self, dim_in, dim_out):
        super(NodeApplyModule, self).__init__()
        self.linear = nn.Linear(dim_in, dim_out)

    def forward(self, node):
        h = self.linear(node.data['h'])
        return {'h': h}

class GCNLayer(nn.Module):
    def __init__(self, dim_in, dim_out):
        super(GCNLayer, self).__init__()
        self.msg = fn.copy_u('h', 'm')
        self.apply_mod = NodeApplyModule(dim_in, dim_out)

    def reduce(self, nodes):
        mbox = nodes.mailbox['m']      # (num_nodes, num_in_edges, dim_in)
        accum = torch.mean(mbox, dim=1)
        return {'h': accum}

    def forward(self, g, feature):
        # forward마다 graph에 임시 feature를 넣으니 local_scope 권장
        with g.local_scope():
            g.ndata['h'] = feature
            g.update_all(self.msg, self.reduce)
            g.apply_nodes(func=self.apply_mod)
            return g.ndata['h']
        
        torch.manual_seed(0)      # Linear 초기화 재현용
layer = GCNLayer(dim_in=2, dim_out=4)

y = layer(g, x)
    
print("\nOutput y:")
print(y)                  # (3, 4)
print("y.shape:", y.shape)


Output y:
tensor([[-0.7681, -0.1208,  0.1879, -0.2347],
        [-0.6043, -0.2150,  0.1336, -0.2604],
        [-0.6043, -0.2150,  0.1336, -0.2604]], grad_fn=<AddmmBackward0>)
y.shape: torch.Size([3, 4])


In [83]:
import numpy as np
import torch
import dgl
from dgl.nn import GraphConv

In [84]:
g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
g = dgl.to_bidirected(g)
g = dgl.add_self_loop(g)
g.num_nodes()
feat = torch.ones(6, 10)
conv = GraphConv(10, 2, norm='both', weight = True, bias = False)
res = conv(g, feat)
res

tensor([[ 0.9533, -0.0866],
        [ 0.9533, -0.0866],
        [ 1.0751, -0.0977],
        [ 1.2046, -0.1095],
        [ 0.8518, -0.0774],
        [ 0.8518, -0.0774]], grad_fn=<MulBackward0>)

In [102]:
g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
g = dgl.to_bidirected(g)
g = dgl.add_self_loop(g)
g.num_nodes()
feat = torch.ones(6, 10)
conv = GraphConv(10, 2, norm='both', weight = True, bias = False)
res = conv(g, feat)
res

tensor([[ 1.1657, -0.3529],
        [ 1.1657, -0.3529],
        [ 1.3146, -0.3980],
        [ 1.4729, -0.4459],
        [ 1.0415, -0.3153],
        [ 1.0415, -0.3153]], grad_fn=<MulBackward0>)

In [63]:
A_tilde = g.adj().to_dense()
A_tilde

tensor([[1., 1., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0.],
        [1., 0., 1., 1., 0., 0.],
        [0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 1.]])

In [66]:
A = g.adj().to_dense()  # 보통 A[src, dst]=1 형태로 생각하면 됨

deg_out = g.out_degrees().float()
deg_in  = g.in_degrees().float()

Dout_inv_sqrt = torch.diag(torch.pow(deg_out, -0.5))
Din_inv_sqrt  = torch.diag(torch.pow(deg_in,  -0.5))

# GraphConv: Din^-1/2 * A^T * Dout^-1/2 * X * W
res2 = Din_inv_sqrt @ A.T @ Dout_inv_sqrt @ feat @ conv.weight
res2

tensor([[ 1.2541, -0.4789],
        [ 1.3808, -0.5273],
        [ 1.2541, -0.4789],
        [ 1.5876, -0.6063],
        [ 1.6667, -0.6365],
        [ 0.9763, -0.3729]], grad_fn=<MmBackward0>)

In [103]:
A_tilde = g.adj().to_dense()
deg = A_tilde.sum(dim=1)
D_tilde = torch.diag(deg)
D_tilde2 = torch.diag(torch.pow(deg, -1/2))
res2 = D_tilde2 @ A_tilde @ D_tilde2 @ feat @ conv.weight
res2

tensor([[ 1.1657, -0.3529],
        [ 1.1657, -0.3529],
        [ 1.3146, -0.3980],
        [ 1.4729, -0.4459],
        [ 1.0415, -0.3153],
        [ 1.0415, -0.3153]], grad_fn=<MmBackward0>)

In [105]:
A_tilde = g.adj().to_dense()
deg = A_tilde.sum(dim=1)
D_tilde = torch.pow(deg, -0.5)

X1 = feat * D_tilde.unsqueeze(-1)
X2 = A_tilde @ X1
X3 = X2 * D_tilde.unsqueeze(-1)
res3 = X3 @ conv.weight
res3

tensor([[ 1.1657, -0.3529],
        [ 1.1657, -0.3529],
        [ 1.3146, -0.3980],
        [ 1.4729, -0.4459],
        [ 1.0415, -0.3153],
        [ 1.0415, -0.3153]], grad_fn=<MmBackward0>)

In [37]:
# Case 1: Homogeneous graph
g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
g = dgl.add_self_loop(g)
feat = th.ones(6, 10)
conv = GraphConv(10, 2, norm='both', weight=True, bias=True)
res = conv(g, feat)
print(res)
# allow_zero_in_degree example
g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
conv = GraphConv(10, 2, norm='both', weight=True, bias=True, allow_zero_in_degree=True)
res = conv(g, feat)
print(res)

tensor([[ 0.0408, -0.1750],
        [ 0.0449, -0.1926],
        [ 0.0408, -0.1750],
        [ 0.0517, -0.2215],
        [ 0.0542, -0.2325],
        [ 0.0318, -0.1362]], grad_fn=<AddBackward0>)
tensor([[-0.6709, -0.9603],
        [-0.9488, -1.3581],
        [-0.9488, -1.3581],
        [-1.1453, -1.6394],
        [-0.9488, -1.3581],
        [ 0.0000,  0.0000]], grad_fn=<AddBackward0>)


In [38]:
# Case 2: Unidirectional bipartite graph
u = [0, 1, 0, 0, 1]
v = [0, 1, 2, 3, 2]
g = dgl.heterograph({('_U', '_E', '_V') : (u, v)})
u_fea = th.rand(2, 5)
v_fea = th.rand(4, 5)
conv = GraphConv(5, 2, norm='both', weight=True, bias=True)
res = conv(g, (u_fea, v_fea))
res

tensor([[ 0.1472, -0.3450],
        [-0.0460, -0.3972],
        [ 0.0715, -0.5248],
        [ 0.1472, -0.3450]], grad_fn=<AddBackward0>)

In [118]:
import numpy as np
import torch
import dgl
from rdkit import Chem
from dgl.nn import GraphConv

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def adj_mat_to_edges(adj_mat):
    edges = []
    for i in range(adj_mat.shape[0]):
        for j in range(adj_mat.shape[1]):
            if adj_mat[i, j] == 1:
                edges.append((i, j))
    return edges

def smiles_to_mol_graph_simple(smiles, feat_dim=16):
    """
    네 코드 흐름과 동일:
    RDKit adjacency -> edges -> DGLGraph + ndata['feat']
    단, props 대신 간단 one-hot feature 사용
    """
    mol = Chem.MolFromSmiles(smiles)
    adj_mat = Chem.GetAdjacencyMatrix(mol)  # (N,N), 대칭(무방향)

    edges = adj_mat_to_edges(adj_mat)
    src, dst = tuple(zip(*edges)) if len(edges) > 0 else ([], [])

    g = dgl.graph((torch.tensor(src), torch.tensor(dst)), num_nodes=adj_mat.shape[0]).to(device)

    # --- node features (간단 예시): atomic number mod feat_dim one-hot ---
    N = mol.GetNumAtoms()
    X = torch.zeros((N, feat_dim), dtype=torch.float32, device=device)
    for i, atom in enumerate(mol.GetAtoms()):
        idx = atom.GetAtomicNum() % feat_dim
        X[i, idx] = 1.0
    g.ndata["feat"] = X
    return mol, g

def check_match_with_paper(smiles="CCO", out_dim=8):
    mol, g = smiles_to_mol_graph_simple(smiles, feat_dim=16)
    g = dgl.add_self_loop(g)  # 논문식 A~ = A + I

    X = g.ndata["feat"]  # (N, Fin)

    # ---- DGL GraphConv ----
    torch.manual_seed(0)
    conv = GraphConv(X.shape[1], out_dim, norm="both", weight=True, bias=False).to(device)

    res = conv(g, X)  # (N, out_dim)

    # ---- 논문식 행렬곱: D~^-1/2 A~ D~^-1/2 X W ----
    # g는 이미 무방향(양방향 edge) + self-loop 상태라 A~는 대칭이어야 함
    A_tilde = g.adj().to_dense()  # (N,N), 보통 float
    deg = A_tilde.sum(dim=1)      # D~_ii = sum_j A~_ij (row-sum)
    D_inv_sqrt = torch.diag(torch.pow(deg, -0.5))
    # Kipf 식 (활성화 σ는 생략: GraphConv도 activation 안 넣으면 동일하게 비교 가능)
    res2 = D_inv_sqrt @ A_tilde @ D_inv_sqrt @ X @ conv.weight

    D_inv_sqrt2 = torch.pow(deg, -0.5)
    X1 = X * D_inv_sqrt2.unsqueeze(-1)
    X2 = A_tilde @ X1
    X3 = X2 * D_inv_sqrt2.unsqueeze(-1)
    res3 = X3 @ conv.weight

    # ---- 비교 ----
    diff = (res - res2).abs().max().item()
    diff2 = (res2 - res3).abs().max().item()
    print("SMILES:", smiles)
    print("num_nodes:", g.num_nodes(), "num_edges:", g.num_edges())
    print("max|res - res2| =", diff)
    print("res[0]:", res[0].detach().cpu())
    print("res2[0]:", res2[0].detach().cpu())
    print("res3[0]:", res3[0].detach().cpu())
    print("max|res2 - res3| =", diff2)

check_match_with_paper("CCO", out_dim=8)   # 에탄올 예시


SMILES: CCO
num_nodes: 3 num_edges: 7
max|res - res2| = 2.9802322387695312e-08
res[0]: tensor([-0.2014, -0.0164,  0.2904,  0.4515,  0.1802,  0.0613,  0.3045, -0.2674])
res2[0]: tensor([-0.2014, -0.0164,  0.2904,  0.4515,  0.1802,  0.0613,  0.3045, -0.2674])
res3[0]: tensor([-0.2014, -0.0164,  0.2904,  0.4515,  0.1802,  0.0613,  0.3045, -0.2674])
max|res2 - res3| = 2.9802322387695312e-08


In [88]:
deg.clamp_min(0.0001)
# deg

tensor([3., 3., 4., 4., 2., 2.])

In [78]:
mol = Chem.MolFromSmiles('COO')
N = mol.GetNumAtoms()
X = torch.zeros((N, 16), dtype=torch.float32, device=device)
for i, atom in enumerate(mol.GetAtoms()):
    idx = atom.GetAtomicNum() % 16
    X[i, idx] = 1.0
g.ndata["feat"] = X

DGLError: Expect number of features to match number of nodes (len(u)). Got 3 and 6 instead.

In [82]:
mol = Chem.MolFromSmiles('CCO')
N = mol.GetNumAtoms()
for i, atom in enumerate(mol.GetAtoms()):
    print(i, atom.GetAtomicNum())

0 6
1 6
2 8


In [116]:

# g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
# g = dgl.to_bidirected(g) # 방향 > 무방향으로 엣지 추가
# g = dgl.add_self_loop(g)
# feat = torch.ones(6, 10)

A_tilde = g.adj().to_dense()
deg = A_tilde.sum(dim=1)
D_tilde = torch.pow(deg, -0.5)

X1 = feat * D_tilde.unsqueeze(-1)
X2 = A_tilde @ X1
X3 = X2 * D_tilde.unsqueeze(-1)
res3 = X3 @ conv.weight
res3

tensor([[0.5214, 0.9105],
        [0.5214, 0.9105],
        [0.5880, 1.0268],
        [0.6588, 1.1505],
        [0.4659, 0.8135],
        [0.4659, 0.8135]], grad_fn=<MmBackward0>)

In [117]:

A_tilde = g.adj().to_dense()
deg = A_tilde.sum(dim=1)
D_tilde = torch.diag(deg)
D_tilde2 = torch.diag(torch.pow(deg, -1/2))
res2 = D_tilde2 @ A_tilde @ D_tilde2 @ feat @ conv.weight
res2

tensor([[0.5214, 0.9105],
        [0.5214, 0.9105],
        [0.5880, 1.0268],
        [0.6588, 1.1505],
        [0.4659, 0.8135],
        [0.4659, 0.8135]], grad_fn=<MmBackward0>)

In [115]:
conv = GraphConv(10, 2, norm='both', weight = True, bias = False)
res = conv(g, feat)
res

tensor([[0.5214, 0.9105],
        [0.5214, 0.9105],
        [0.5880, 1.0268],
        [0.6588, 1.1505],
        [0.4659, 0.8135],
        [0.4659, 0.8135]], grad_fn=<MulBackward0>)

In [1]:
import torch

In [68]:
# -------------------------
# 설정
# -------------------------
B, H, N, T = 1, 2, 1, 4

# Attention map A : (B, H, N, T)
A = torch.tensor(
    [[
        # head 0
        [[0.1, 0.2, 0.3, 0.4]],

        # head 1
        [[1.1, 1.2, 1.3, 1.4]],
    ]]
)

print("A shape:", A.shape)
print("A before mask:\n", A)


A shape: torch.Size([1, 2, 1, 4])
A before mask:
 tensor([[[[0.1000, 0.2000, 0.3000, 0.4000]],

         [[1.1000, 1.2000, 1.3000, 1.4000]]]])


In [72]:
A.view(B,1,1,T*2)

tensor([[[[0.1000, 0.2000, 0.3000, 0.4000, 1.1000, 1.2000, 1.3000, 1.4000]]]])

In [11]:
# frame_mask : (B, 1, 1, T)
# t=2 프레임만 invalid (0)
frame_mask = torch.tensor([[[[1, 1, 0, 1]]]])

print("\nframe_mask shape:", frame_mask.shape)
print("frame_mask:\n", frame_mask)



frame_mask shape: torch.Size([1, 1, 1, 4])
frame_mask:
 tensor([[[[1, 1, 0, 1]]]])


In [20]:
frame_mask.view(1,1,1,4)

tensor([[[[1, 1, 0, 1]]]])

In [14]:
A[0, :, :, 2]

tensor([[0.3000, 0.7000, 1.1000],
        [1.3000, 1.7000, 2.1000]])

In [8]:
A_masked = A * frame_mask
print("\nA after mask:\n", A_masked)



A after mask:
 tensor([[[[0.1000, 0.2000, 0.0000, 0.4000],
          [0.5000, 0.6000, 0.0000, 0.8000],
          [0.9000, 1.0000, 0.0000, 1.2000]],

         [[1.1000, 1.2000, 0.0000, 1.4000],
          [1.5000, 1.6000, 0.0000, 1.8000],
          [1.9000, 2.0000, 0.0000, 2.2000]]]])


In [10]:
A[0, :, :, 2]

tensor([[0.3000, 0.7000, 1.1000],
        [1.3000, 1.7000, 2.1000]])

In [16]:
A_masked[0, :, :, 2]

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
class MultiHeadSparsityLoss(nn.Module):
    def __init__(self, eps: float = 1e-12, reduction: str = "mean"):
        super().__init__()
        self.eps = eps
        assert reduction in ("mean", "sum", "none")
        self.reduction = reduction

    def forward(self, A: torch.Tensor, frame_mask: torch.Tensor = None) -> torch.Tensor:
        if A.ndim == 3:
            A = A.unsqueeze(1) # (B,N,T) -> (B,1,N,T)
        elif A.ndim != 4:
            raise ValueError("A must be (B,H,N,T) or (B,N,T).")

        B, H, N, T = A.shape

        # frame_mask: allow (B,T), (B,1,T), (B,1,1,T)
        if frame_mask is not None:
            if frame_mask.ndim == 2:          # (B,T)
                frame_mask = frame_mask[:, None, None, :]     # (B,1,1,T)
            elif frame_mask.ndim == 3:        # (B,1,T)
                frame_mask = frame_mask[:, None, :, :]        # (B,1,1,T) if middle dim==1
                if frame_mask.shape[2] != 1:
                    raise ValueError("frame_mask with ndim=3 must be (B,1,T).")
            elif frame_mask.ndim == 4:        # (B,1,1,T)
                if frame_mask.shape[1:3] != (1,1):
                    raise ValueError("frame_mask with ndim=4 must be (B,1,1,T).")
            else:
                raise ValueError("frame_mask must be (B,T), (B,1,T), or (B,1,1,T).")

            frame_mask = frame_mask.view(B, 1, 1, T)
            A = A * frame_mask  # zero-out invalid frames

        # Head-wise normalization by total sum over (N,T)
        sums = A.sum(dim=(2, 3), keepdim=True).clamp_min(self.eps) # (B,H,1,1)
        A_tilde = A / sums # (B,H,N,T)

        # Entropy
        L_sparse_h = -torch.sum(A_tilde * torch.log(A_tilde+self.eps), axis=(2,3))
        print('L_sparse_h:', L_sparse_h.shape)

        # Average over heads
        L_sparse = L_sparse_h.mean(dim=1) # (B,)
        print(L_sparse)
        if self.reduction == "mean":
            return L_sparse.mean()
        elif self.reduction == "sum":
            return L_sparse.sum()
        else:
            return L_sparse  # (B,)



In [84]:
# -*- coding: utf-8 -*-
import torch
import torch.nn as nn

class MultiHeadSparsityLoss(nn.Module):
    def __init__(self, eps: float = 1e-12, reduction: str = "mean"):
        super().__init__()
        self.eps = eps
        assert reduction in ("mean", "sum", "none")
        self.reduction = reduction

    def forward(self, A: torch.Tensor, frame_mask: torch.Tensor = None) -> torch.Tensor:
        if A.ndim == 3:
            A = A.unsqueeze(1) # (B,N,T) -> (B,1,N,T)
        elif A.ndim != 4:
            raise ValueError("A must be (B,H,N,T) or (B,N,T).")

        B, H, N, T = A.shape

        # frame_mask: allow (B,T), (B,1,T), (B,1,1,T)
        if frame_mask is not None:
            if frame_mask.ndim == 2:          # (B,T)
                frame_mask = frame_mask[:, None, None, :]     # (B,1,1,T)
            elif frame_mask.ndim == 3:        # (B,1,T)
                frame_mask = frame_mask[:, None, :, :]        # (B,1,1,T) if middle dim==1
                if frame_mask.shape[2] != 1:
                    raise ValueError("frame_mask with ndim=3 must be (B,1,T).")
            elif frame_mask.ndim == 4:        # (B,1,1,T)
                if frame_mask.shape[1:3] != (1,1):
                    raise ValueError("frame_mask with ndim=4 must be (B,1,1,T).")
            else:
                raise ValueError("frame_mask must be (B,T), (B,1,T), or (B,1,1,T).")

            frame_mask = frame_mask.view(B, 1, 1, T)
            A = A * frame_mask  # zero-out invalid frames

        # Head-wise normalization by total sum over (N,T)
        sums = A.sum(dim=(2, 3), keepdim=True).clamp_min(self.eps) # (B,H,1,1)
        A_tilde = A / sums # (B,H,N,T)

        # Entropy
        L_sparse_h = -torch.sum(A_tilde * torch.log(A_tilde+self.eps), axis=(2,3))
        print('L_sparse_h:', L_sparse_h.shape)

        # Average over heads
        L_sparse = L_sparse_h.mean(dim=1) # (B,)
        print(L_sparse)
        if self.reduction == "mean":
            return L_sparse.mean()
        elif self.reduction == "sum":
            return L_sparse.sum()
        else:
            return L_sparse  # (B,)


# ---------------------------
# 사용 예시
# ---------------------------
if __name__ == "__main__":
    B, H, N, T = 8, 4, 25, 48
    A = torch.rand(B, H, N, T, requires_grad=True)  # 예시 attention
    y = torch.randint(0, 300, (B,))                 # 예시 라벨
    logits = torch.randn(B, 300, requires_grad=True)

    # 손실들
    ce = nn.CrossEntropyLoss()(logits, y)

    sparse_loss_fn = MultiHeadSparsityLoss(eps=1e-12, reduction="mean")
    L_sparse = sparse_loss_fn(A)  # \mathcal{L}_{sparse}

    # 가중합 (예: lambda_s = 0.1)
    lambda_s = 0.1
    loss = ce + lambda_s * L_sparse
    loss.backward()

    print('L_sparse:', L_sparse)

L_sparse_h: torch.Size([8, 4])
tensor([6.8965, 6.9004, 6.9001, 6.8937, 6.8916, 6.8958, 6.8991, 6.8901],
       grad_fn=<MeanBackward1>)
L_sparse: tensor(6.8959, grad_fn=<MeanBackward0>)


In [134]:
import torch.nn.functional as F

class MultiHeadDiversityLoss(nn.Module):
    def __init__(self, eps: float = 1e-12, reduction: str = "mean"):
        super().__init__()
        assert reduction in ("mean", "sum", "none")
        self.eps = eps
        self.reduction = reduction

    def forward(self, A: torch.Tensor, frame_mask: torch.Tensor = None) -> torch.Tensor:
        if A.ndim == 3:
            A = A.unsqueeze(1) # (B,N,T) -> (B,1,N,T)
        elif A.ndim != 4:
            raise ValueError("A must be (B,H,N,T) or (B,N,T).")

        B, H, N, T = A.shape

        # frame_mask: allow (B,T), (B,1,T), (B,1,1,T)
        if frame_mask is not None:
            if frame_mask.ndim == 2:          # (B,T)
                frame_mask = frame_mask[:, None, None, :]     # (B,1,1,T)
            elif frame_mask.ndim == 3:        # (B,1,T)
                if frame_mask.shape[2] != 1:
                    raise ValueError("frame_mask with ndim=3 must be (B,1,T).")
                frame_mask = frame_mask[:, None, :, :]        # (B,1,1,T) if middle dim==1
            elif frame_mask.ndim == 4:        # (B,1,1,T)
                if frame_mask.shape[1:3] != (1,1):
                    raise ValueError("frame_mask with ndim=4 must be (B,1,1,T).")
            else:
                raise ValueError("frame_mask must be (B,T), (B,1,T), or (B,1,1,T).")

            frame_mask = frame_mask.view(B, 1, 1, T)
            A = A * frame_mask  # zero-out invalid frames

        # Head-wise normalization by total sum over (N,T)
        sums = A.sum(dim=(2, 3), keepdim=True).clamp_min(self.eps) # (B,H,1,1)
        A_tilde = A / sums # (B,H,N,T)

        # Vectorize per head
        A_vec = A_tilde.reshape(B, H, N*T)

        # L2-normalize per head vector
        A_hat = F.normalize(A_vec, dim=2, eps=self.eps) # (B,H,NT)

        # If H == 1, no pair exists -> loss = 0
        if H <= 1:
            zero = A_hat.new_zeros(B)
            if self.reduction == "mean":
                return zero.mean()
            elif self.reduction == "sum":
                return zero.sum()
            else:
                return zero  # (B,)

        # squared cosine similarity
        G = torch.bmm(A_hat, A_hat.transpose(1, 2)) # (B,H,H)
        G2 = G.pow(2)                                        

        triu_mask = torch.triu(torch.ones(H, H, dtype=torch.bool, device=A_hat.device), diagonal=1)
        pair_sums = G2[:, triu_mask].sum(dim=1) # (B,)

        L_div_per_sample = (2.0 / (H * (H - 1))) * pair_sums # (B,)

        # Reduction over batch
        if self.reduction == "mean":
            return L_div_per_sample.mean()
        elif self.reduction == "sum":
            return L_div_per_sample.sum()
        else:
            return L_div_per_sample  # (B,)


In [136]:
if __name__ == "__main__":
    B, H, N, T = 8, 4, 25, 48
    # 예시 attention (이미 head-wise 정규화된 형태를 권장하지만, 아래 구현은 L2정규화도 적용)
    A = torch.rand(B, H, N, T, requires_grad=True)

    # diversity loss
    div_loss_fn = MultiHeadDiversityLoss()
    L_div = div_loss_fn(A)  # \mathcal{L}_{div}

    # 다른 손실과 결합 예시
    logits = torch.randn(B, 300, requires_grad=True)
    y = torch.randint(0, 300, (B,))
    ce = nn.CrossEntropyLoss()(logits, y)

    lambda_div = 0.05
    loss = ce + lambda_div * L_div
    loss.backward()
    print(loss)

tensor(6.6615, grad_fn=<AddBackward0>)


In [112]:

H = 3
triu_mask = torch.triu(
    torch.ones(H, H, dtype=torch.bool),
    diagonal=1
)

print(triu_mask)


tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])


In [113]:
# 배치 1개, H=3
G2 = torch.tensor([[
    [1.00, 0.20, 0.30],
    [0.20, 1.00, 0.40],
    [0.30, 0.40, 1.00]
]])

print("G2 shape:", G2.shape)
print(G2)


G2 shape: torch.Size([1, 3, 3])
tensor([[[1.0000, 0.2000, 0.3000],
         [0.2000, 1.0000, 0.4000],
         [0.3000, 0.4000, 1.0000]]])


In [114]:
selected = G2[:, triu_mask]
print(selected)
print(selected.shape)


tensor([[0.2000, 0.3000, 0.4000]])
torch.Size([1, 3])


In [117]:
G2[:,]

tensor([[[1.0000, 0.2000, 0.3000],
         [0.2000, 1.0000, 0.4000],
         [0.3000, 0.4000, 1.0000]]])

In [118]:
G2[:,].sum(dim=1)

tensor([[1.5000, 1.6000, 1.7000]])

In [2]:
import torch
import torch.nn as nn

# -----------------------------
# Descriptor Tokenizer 정의
# -----------------------------
class Descriptor_Tokenizer(nn.Module):
    def __init__(self, d_desc: int, d_t: int):
        super().__init__()

        self.val_embedding = nn.Linear(1, d_t)
        self.id_embedding = nn.Embedding(d_desc, d_t)

        self.num_desc = d_desc
        self.d_t = d_t

    def forward(self, descriptor: torch.Tensor):
        B, D = descriptor.shape

        # value embedding
        desc = descriptor.unsqueeze(-1)        # (B, D) -> (B, D, 1)
        val_emb = self.val_embedding(desc)     # (B, D, d_t)

        # ID embedding
        ids = torch.arange(D, device=descriptor.device)
        id_emb = self.id_embedding(ids)        # (D, d_t)
        id_emb = id_emb.unsqueeze(0).expand(B, -1, -1)

        desc_tks = val_emb + id_emb

        return desc_tks, val_emb, id_emb


# -----------------------------
# 테스트 실행
# -----------------------------
if __name__ == "__main__":
    torch.manual_seed(0)

    B = 2     # batch size (분자 2개)
    D = 5     # descriptor 개수
    d_t = 4   # token dimension

    tokenizer = Descriptor_Tokenizer(d_desc=D, d_t=d_t)

    # 예시 descriptor 입력
    desc = torch.tensor([
        [1.0, 2.0, 3.0, 4.0, 5.0],
        [5.0, 4.0, 3.0, 2.0, 1.0],
    ])

    tokens, val_emb, id_emb = tokenizer(desc)

    print("Input descriptor shape:", desc.shape)
    print("Value embedding shape:", val_emb.shape)
    print("ID embedding shape:", id_emb.shape)
    print("Token shape:", tokens.shape)

    print("\nDescriptor[0] value embedding:")
    print(val_emb[0])

    print("\nDescriptor ID embedding:")
    print(id_emb[0])

    print("\nFinal token = value + ID:")
    print(tokens[0])


Input descriptor shape: torch.Size([2, 5])
Value embedding shape: torch.Size([2, 5, 4])
ID embedding shape: torch.Size([2, 5, 4])
Token shape: torch.Size([2, 5, 4])

Descriptor[0] value embedding:
tensor([[-0.3926,  0.8046, -0.8429,  0.0570],
        [-0.4001,  1.3410, -1.6659, -0.6790],
        [-0.4076,  1.8775, -2.4889, -1.4149],
        [-0.4151,  2.4139, -3.3120, -2.1509],
        [-0.4226,  2.9504, -4.1350, -2.8868]], grad_fn=<SelectBackward0>)

Descriptor ID embedding:
tensor([[-0.3561,  0.4372,  0.4913, -0.2041],
        [ 0.1665,  0.8744, -0.1435, -0.1116],
        [-0.6136,  0.0316, -0.4927,  0.2484],
        [ 0.6181, -0.4128, -0.8411, -2.3160],
        [-0.1023,  0.7924, -0.2897,  0.0525]], grad_fn=<SelectBackward0>)

Final token = value + ID:
tensor([[-0.7488,  1.2418, -0.3516, -0.1472],
        [-0.2337,  2.2154, -1.8094, -0.7906],
        [-1.0212,  1.9091, -2.9816, -1.1665],
        [ 0.2030,  2.0011, -4.1531, -4.4669],
        [-0.5249,  3.7428, -4.4247, -2.8343]], gra

In [11]:
a = nn.Embedding(5,4 )
idx = torch.arange(5)

In [12]:
a(idx)

tensor([[ 0.5851, -1.1560, -0.1434, -0.1947],
        [-0.9069, -0.5918,  0.1508, -1.0411],
        [-0.7205, -2.2148, -0.6837,  0.5164],
        [ 0.7928,  0.0832,  0.4228, -1.8687],
        [-1.1057,  0.1437,  0.5836,  1.3482]], grad_fn=<EmbeddingBackward0>)

In [20]:
idx = torch.arange(5)
id_emb = a(idx)

In [21]:
id_emb.unsqueeze(0).expand(32,-1,-1)

tensor([[[ 0.5851, -1.1560, -0.1434, -0.1947],
         [-0.9069, -0.5918,  0.1508, -1.0411],
         [-0.7205, -2.2148, -0.6837,  0.5164],
         [ 0.7928,  0.0832,  0.4228, -1.8687],
         [-1.1057,  0.1437,  0.5836,  1.3482]],

        [[ 0.5851, -1.1560, -0.1434, -0.1947],
         [-0.9069, -0.5918,  0.1508, -1.0411],
         [-0.7205, -2.2148, -0.6837,  0.5164],
         [ 0.7928,  0.0832,  0.4228, -1.8687],
         [-1.1057,  0.1437,  0.5836,  1.3482]],

        [[ 0.5851, -1.1560, -0.1434, -0.1947],
         [-0.9069, -0.5918,  0.1508, -1.0411],
         [-0.7205, -2.2148, -0.6837,  0.5164],
         [ 0.7928,  0.0832,  0.4228, -1.8687],
         [-1.1057,  0.1437,  0.5836,  1.3482]],

        [[ 0.5851, -1.1560, -0.1434, -0.1947],
         [-0.9069, -0.5918,  0.1508, -1.0411],
         [-0.7205, -2.2148, -0.6837,  0.5164],
         [ 0.7928,  0.0832,  0.4228, -1.8687],
         [-1.1057,  0.1437,  0.5836,  1.3482]],

        [[ 0.5851, -1.1560, -0.1434, -0.1947],
     

In [23]:
val_embedding  = nn.Linear(1, 4)
val_embedding(4)

TypeError: linear(): argument 'input' (position 1) must be Tensor, not int

In [ ]:
import torch
import torch.nn as nn

torch.manual_seed(0)

# ----------------------------
# Descriptor Tokenizer
# ----------------------------
class Descriptor_Tokenizer(nn.Module):
    def __init__(self, d_desc: int, d_t: int):
        super().__init__()

        # value embedding
        self.val_embedding = nn.Linear(1, d_t)

        # descriptor identity embedding
        self.id_embedding = nn.Embedding(d_desc, d_t)

    def forward(self, descriptor):
        B, D = descriptor.shape

        # value embedding
        desc = descriptor.unsqueeze(-1)      # (B, D) -> (B, D, 1)
        val_emb = self.val_embedding(desc)   # (B, D, d_t)

        # ID embedding
        ids = torch.arange(D) # (D, )
        id_emb = self.id_embedding(ids)      # (D, d_t)
        id_emb = id_emb.unsqueeze(0).expand(B, -1, -1)

        tokens = val_emb + id_emb

        return tokens, val_emb, id_emb


# ----------------------------
# 테스트 입력
# ----------------------------
B = 5   # 분자 개수
D = 3   # descriptor 개수
d_t = 4 # token dimension

tokenizer = Descriptor_Tokenizer(d_desc=D, d_t=d_t)

# (5,3) descriptor 예제
descriptor = torch.tensor([
    [1.0, 2.0, 3.0],
    [3.0, 2.0, 1.0],
    [4.0, 5.0, 6.0],
    [6.0, 5.0, 4.0],
    [1.5, 2.5, 3.5],
])

tokens, val_emb, id_emb = tokenizer(descriptor)

print("Descriptor shape:", descriptor.shape)
print("Value embedding:", val_emb.shape)
print("ID embedding:", id_emb.shape)
print("Final tokens:", tokens.shape)

print("\nDescriptor input:")
print(descriptor)

print("\nValue embedding (분자마다 다름):")
print(val_emb)

print("\nID embedding (batch마다 동일):")
print(id_emb)

print("\nFinal tokens = value + ID:")
print(tokens)


Descriptor shape: torch.Size([5, 3])
Value embedding: torch.Size([5, 3, 4])
ID embedding: torch.Size([5, 3, 4])
Final tokens: torch.Size([5, 3, 4])

Descriptor input:
tensor([[1.0000, 2.0000, 3.0000],
        [3.0000, 2.0000, 1.0000],
        [4.0000, 5.0000, 6.0000],
        [6.0000, 5.0000, 4.0000],
        [1.5000, 2.5000, 3.5000]])

Value embedding (분자마다 다름):
tensor([[[-0.3926,  0.8046, -0.8429,  0.0570],
         [-0.4001,  1.3410, -1.6659, -0.6790],
         [-0.4076,  1.8775, -2.4889, -1.4149]],

        [[-0.4076,  1.8775, -2.4889, -1.4149],
         [-0.4001,  1.3410, -1.6659, -0.6790],
         [-0.3926,  0.8046, -0.8429,  0.0570]],

        [[-0.4151,  2.4139, -3.3120, -2.1509],
         [-0.4226,  2.9504, -4.1350, -2.8868],
         [-0.4301,  3.4868, -4.9581, -3.6227]],

        [[-0.4301,  3.4868, -4.9581, -3.6227],
         [-0.4226,  2.9504, -4.1350, -2.8868],
         [-0.4151,  2.4139, -3.3120, -2.1509]],

        [[-0.3964,  1.0728, -1.2544, -0.3110],
         [-0.40