In [1]:
import torch

In [2]:
A = torch.randn(3,3) # Normal 의 n
B = torch.rand(3,3) # 이건 uniform

print(A)
print(B)

tensor([[-0.0895, -0.1527, -0.5851],
        [-0.5845, -0.4716, -0.5187],
        [-2.0829, -1.8987, -0.2065]])
tensor([[0.4309, 0.2573, 0.2111],
        [0.2830, 0.9468, 0.3256],
        [0.5520, 0.5918, 0.9177]])


In [8]:
torch.floor(A)

tensor([[-2., -1., -2.],
        [ 0., -1., -1.],
        [ 1.,  1.,  0.]])

In [9]:
# torch.abs()
A = torch.randn(3, 3)

print(A)
print(torch.abs(A))

tensor([[ 0.1172, -0.7585,  0.5978],
        [ 0.7320,  0.0827, -0.6457],
        [-0.9274,  0.5196, -0.1786]])
tensor([[0.1172, 0.7585, 0.5978],
        [0.7320, 0.0827, 0.6457],
        [0.9274, 0.5196, 0.1786]])


In [ ]:
# torch.sqrt()
A = torch.randn(3, 3)

print(A)
print(torch.sqrt(torch.abs(A)))

tensor([[ 0.8412, -1.1415,  0.3658],
        [ 1.4939, -1.1553,  0.2184],
        [ 1.4429,  1.2290, -0.5289]])
tensor([[0.9172, 1.0684, 0.6048],
        [1.2223, 1.0748, 0.4674],
        [1.2012, 1.1086, 0.7272]])


In [11]:
# torch.exp()
A = torch.randn(3, 3)

print(A)
print(torch.exp(A))

tensor([[ 0.9844,  0.2728,  0.1605],
        [-1.6301,  0.2603, -1.9631],
        [-0.0500,  0.8533,  1.1820]])
tensor([[2.6763, 1.3136, 1.1742],
        [0.1959, 1.2973, 0.1404],
        [0.9513, 2.3474, 3.2609]])


In [15]:
# torch.log()
A = torch.randn(3, 3)

print(A)
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1))))
#print(torch.log(torch.exp(1))) # error

print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))

tensor([[ 0.5399, -0.1466,  0.8977],
        [-1.5797, -0.7181,  1.2293],
        [ 1.4188,  1.6415,  0.1050]])
tensor([[-0.6163, -1.9202, -0.1079],
        [ 0.4572, -0.3311,  0.2065],
        [ 0.3498,  0.4956, -2.2540]])
tensor(1.)
tensor(1.)
tensor(1.)


In [ ]:
# torch.round() / torch.floor() / torch.ceil()
A = torch.randn(3, 3)

print(A)
print(torch.round(A))
print(torch.round(A, decimals = 2)) # 소수점 둘째자리까지

print(torch.floor(A))
print(torch.ceil(A))

tensor([[-0.8339, -0.1697, -0.2437],
        [ 0.7478,  1.8171,  0.9521],
        [ 0.8335, -0.3031,  1.0360]])
tensor([[-1., -0., -0.],
        [ 1.,  2.,  1.],
        [ 1., -0.,  1.]])
tensor([[-0.8300, -0.1700, -0.2400],
        [ 0.7500,  1.8200,  0.9500],
        [ 0.8300, -0.3000,  1.0400]])
tensor([[-1., -1., -1.],
        [ 0.,  1.,  0.],
        [ 0., -1.,  1.]])
tensor([[-0., -0., -0.],
        [1., 2., 1.],
        [1., -0., 2.]])


In [ ]:
# torch.sin() / torch.cos() / torch.tan() / torch.tanh()
print(torch.sin(torch.tensor(torch.pi/6))) # sin 30도
print(torch.cos(torch.tensor(torch.pi/3))) # cos 60도
print(torch.tan(torch.tensor(torch.pi/4))) # tan 45도

print(torch.tanh(torch.tensor(-10)))

# torch.pi는 float이라서 tensor로 변경해줘야 사용 가능
print(type(torch.pi))
print(type(torch.tensor(torch.pi/6)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)
<class 'float'>
<class 'torch.Tensor'>


In [ ]:
# torch.nan / torch.isnan() / torch.isinf()
print(torch.nan) # not a number

print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1, 2, torch.nan, 3, 4])))
print(torch.isinf(torch.tensor([1, 2, 3, 4, torch.inf])))

nan
tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
# torch.max()
A = torch.randn(3,4)
print(A)

# 3x4 중 가장 큰 값
print(torch.max(A)) 

# 0번째 dimension 방향으로 각각 가장 큰 값.
# 즉, 4개의 값이 나옴
print(torch.max(A, dim = 0))

# 1번째 dimension 방향으로 각각 가장 큰 값.
# 즉, 3개의 값이 나옴
print(torch.max(A, dim = 1)) 

# 0번째 dimension 방향으로 각각 가장 큰 값.
# 그리고 dimension은 유지
print(torch.max(A, dim = 0, keepdim = True)) 

# 1번째 dimension 방향으로 각각 가장 큰 값.
# 그리고 dimension은 유지.
# 즉, 3x1 짜리 2D tensor
print(torch.max(A, dim = 1, keepdim = True))

tensor([[-1.1458, -0.5573, -1.5921, -1.0514],
        [-0.5857,  0.6137, -0.7344, -1.3591],
        [-0.9215,  0.3135,  0.5613,  0.8570]])
tensor(0.8570)
torch.return_types.max(
values=tensor([-0.5857,  0.6137,  0.5613,  0.8570]),
indices=tensor([1, 1, 2, 2]))
torch.return_types.max(
values=tensor([-0.5573,  0.6137,  0.8570]),
indices=tensor([1, 1, 3]))
torch.return_types.max(
values=tensor([[-0.5857,  0.6137,  0.5613,  0.8570]]),
indices=tensor([[1, 1, 2, 2]]))
torch.return_types.max(
values=tensor([[-0.5573],
        [ 0.6137],
        [ 0.8570]]),
indices=tensor([[1],
        [1],
        [3]]))


In [ ]:
# torch.argmax()
A = torch.randn(3,4)
print(A)

print(torch.argmax(A))

# 각 열에서 가장 큰 값이 존재하는 인덱스
print(torch.argmax(A,dim=0))

# 각 행에서 가장 큰 값이 존재하는 인덱스
print(torch.argmax(A,dim=1))

tensor([[ 0.2271, -0.8179,  1.3430,  0.3997],
        [ 0.1429,  0.3335,  0.0851, -1.7514],
        [ 1.9710, -1.3510,  1.1681, -0.3809]])
tensor(8)
tensor([2, 1, 0, 0])
tensor([2, 1, 0])


In [ ]:
# torch.sort()
a = torch.randn(6,1)
print(a)

a_sorted = torch.sort(a, dim = 0) # 기본 오름차순 정렬
print(a_sorted)

a_sorted = torch.sort(a, dim = 0, descending = True) # 내림차순 정렬
print(a_sorted)


tensor([[-1.8518],
        [ 0.9623],
        [-0.7140],
        [ 1.4051],
        [-1.3720],
        [-0.2899]])
torch.return_types.sort(
values=tensor([[-1.8518],
        [-1.3720],
        [-0.7140],
        [-0.2899],
        [ 0.9623],
        [ 1.4051]]),
indices=tensor([[0],
        [4],
        [2],
        [5],
        [1],
        [3]]))
torch.return_types.sort(
values=tensor([[ 1.4051],
        [ 0.9623],
        [-0.2899],
        [-0.7140],
        [-1.3720],
        [-1.8518]]),
indices=tensor([[3],
        [1],
        [5],
        [2],
        [4],
        [0]]))


In [ ]:
# torch.mean()
t = 2 * torch.rand(5, 2) - 1
print(t)

# 텐서의 전체 평균  
t1 = torch.mean(t)
print(t1)
print()

t2 = torch.mean(t, axis = 0)
t22 = torch.mean(t, dim = 0)
t222 = torch.mean(t, dim = 0, keepdim = True)
print(t2)
print(t22)
print(t222)
print()

t3 = torch.mean(t, axis = 1)
t33 = torch.mean(t, dim = 1)
t333 = torch.mean(t, dim = 1, keepdim = True)
print(t3)
print(t33)
print(t333)

tensor([[-0.5418, -0.3837],
        [-0.5920,  0.6408],
        [ 0.9517,  0.5600],
        [ 0.7042,  0.1876],
        [-0.2711,  0.8541]])
tensor(0.2110)

tensor([0.0502, 0.3717])
tensor([0.0502, 0.3717])
tensor([[0.0502, 0.3717]])

tensor([-0.4627,  0.0244,  0.7558,  0.4459,  0.2915])
tensor([-0.4627,  0.0244,  0.7558,  0.4459,  0.2915])
tensor([[-0.4627],
        [ 0.0244],
        [ 0.7558],
        [ 0.4459],
        [ 0.2915]])


In [ ]:
# torch.reshape()
A = torch.randint(1, 5, size = (12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B = A.reshape(2, 2, 3)
print(B)
print(B.ndim) # 3 차원 행렬이다

t = torch.zeros(10)
print(t)
print(t.shape)

t_reshape = t.reshape(2, 5)
print(t_reshape)
print(t_reshape.shape)

tensor([1, 1, 2, 3, 4, 1, 3, 4, 4, 2, 2, 4])
torch.Size([12])
tensor([[[1, 1, 2],
         [3, 4, 1]],

        [[3, 4, 4],
         [2, 2, 4]]])
3
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


In [ ]:
# 56분