In [1]:
import torch

In [ ]:
A = torch.randn(3,3) # Normal 의 n
B = torch.rand(3,3) # 이건 uniform

print(A)
print(B)

tensor([[ 1.2674,  0.0054,  1.5042],
        [-1.1128,  0.7905,  0.2445],
        [-0.7501,  1.2293,  1.2374]])
tensor([[0.2904, 0.6580, 0.8337],
        [0.6349, 0.3088, 0.7429],
        [0.3228, 0.9054, 0.2995]])


In [ ]:
A = torch.randn(3,3)

print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 0.0684, -0.2011,  1.8066],
        [-0.6244, -1.1444,  1.3202],
        [-0.0258, -1.4083, -0.6761]])
tensor([[0.0684, 0.2011, 1.8066],
        [0.6244, 1.1444, 1.3202],
        [0.0258, 1.4083, 0.6761]])
tensor([[0.2615, 0.4484, 1.3441],
        [0.7902, 1.0698, 1.1490],
        [0.1606, 1.1867, 0.8222]])
tensor([[1.0708, 0.8178, 6.0899],
        [0.5356, 0.3184, 3.7442],
        [0.9745, 0.2446, 0.5086]])
tensor([[-2.6827, -1.6041,  0.5915],
        [-0.4710,  0.1349,  0.2778],
        [-3.6579,  0.3424, -0.3914]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[ 0., -0.,  2.],
        [-1., -1.,  1.],
        [-0., -1., -1.]])
tensor([[ 0.0700, -0.2000,  1.8100],
        [-0.6200, -1.1400,  1.3200],
        [-0.0300, -1.4100, -0.6800]])
tensor([[ 0., -1.,  1.],
        [-1., -2.,  1.],
        [-1., -2., -1.]])
tensor([[ 1., -0.,  2.],
        [-0., -1.,  2.],
        [-0., -1., -0.]])


In [ ]:
# 46분 위꺼 봐야함