In [1]:
import torch

In [2]:
A = torch.randn(3,3) # Normal 의 n
B = torch.rand(3,3) # 이건 uniform

print(A)
print(B)

tensor([[-0.0895, -0.1527, -0.5851],
        [-0.5845, -0.4716, -0.5187],
        [-2.0829, -1.8987, -0.2065]])
tensor([[0.4309, 0.2573, 0.2111],
        [0.2830, 0.9468, 0.3256],
        [0.5520, 0.5918, 0.9177]])


In [8]:
torch.floor(A)

tensor([[-2., -1., -2.],
        [ 0., -1., -1.],
        [ 1.,  1.,  0.]])

In [9]:
# torch.abs()
A = torch.randn(3, 3)

print(A)
print(torch.abs(A))

tensor([[ 0.1172, -0.7585,  0.5978],
        [ 0.7320,  0.0827, -0.6457],
        [-0.9274,  0.5196, -0.1786]])
tensor([[0.1172, 0.7585, 0.5978],
        [0.7320, 0.0827, 0.6457],
        [0.9274, 0.5196, 0.1786]])


In [ ]:
# torch.sqrt()
A = torch.randn(3, 3)

print(A)
print(torch.sqrt(torch.abs(A)))

tensor([[ 0.8412, -1.1415,  0.3658],
        [ 1.4939, -1.1553,  0.2184],
        [ 1.4429,  1.2290, -0.5289]])
tensor([[0.9172, 1.0684, 0.6048],
        [1.2223, 1.0748, 0.4674],
        [1.2012, 1.1086, 0.7272]])


In [11]:
# torch.exp()
A = torch.randn(3, 3)

print(A)
print(torch.exp(A))

tensor([[ 0.9844,  0.2728,  0.1605],
        [-1.6301,  0.2603, -1.9631],
        [-0.0500,  0.8533,  1.1820]])
tensor([[2.6763, 1.3136, 1.1742],
        [0.1959, 1.2973, 0.1404],
        [0.9513, 2.3474, 3.2609]])


In [15]:
# torch.log()
A = torch.randn(3, 3)

print(A)
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1))))
#print(torch.log(torch.exp(1))) # error

print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))

tensor([[ 0.5399, -0.1466,  0.8977],
        [-1.5797, -0.7181,  1.2293],
        [ 1.4188,  1.6415,  0.1050]])
tensor([[-0.6163, -1.9202, -0.1079],
        [ 0.4572, -0.3311,  0.2065],
        [ 0.3498,  0.4956, -2.2540]])
tensor(1.)
tensor(1.)
tensor(1.)


In [ ]:
# torch.round() / torch.floor() / torch.ceil()
A = torch.randn(3, 3)

print(A)
print(torch.round(A))
print(torch.round(A, decimals = 2)) # 소수점 둘째자리까지

print(torch.floor(A))
print(torch.ceil(A))

tensor([[-0.8339, -0.1697, -0.2437],
        [ 0.7478,  1.8171,  0.9521],
        [ 0.8335, -0.3031,  1.0360]])
tensor([[-1., -0., -0.],
        [ 1.,  2.,  1.],
        [ 1., -0.,  1.]])
tensor([[-0.8300, -0.1700, -0.2400],
        [ 0.7500,  1.8200,  0.9500],
        [ 0.8300, -0.3000,  1.0400]])
tensor([[-1., -1., -1.],
        [ 0.,  1.,  0.],
        [ 0., -1.,  1.]])
tensor([[-0., -0., -0.],
        [1., 2., 1.],
        [1., -0., 2.]])


In [ ]:
# torch.sin() / torch.cos() / torch.tan() / torch.tanh()
print(torch.sin(torch.tensor(torch.pi/6))) # sin 30도
print(torch.cos(torch.tensor(torch.pi/3))) # cos 60도
print(torch.tan(torch.tensor(torch.pi/4))) # tan 45도

print(torch.tanh(torch.tensor(-10)))

# torch.pi는 float이라서 tensor로 변경해줘야 사용 가능
print(type(torch.pi))
print(type(torch.tensor(torch.pi/6)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)
<class 'float'>
<class 'torch.Tensor'>


In [ ]:
# torch.nan / torch.isnan() / torch.isinf()
print(torch.nan) # not a number

print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1, 2, torch.nan, 3, 4])))
print(torch.isinf(torch.tensor([1, 2, 3, 4, torch.inf])))

nan
tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
# torch.max()
A = torch.randn(3,4)
print(A)

# 3x4 중 가장 큰 값
print(torch.max(A)) 

# 0번째 dimension 방향으로 각각 가장 큰 값.
# 즉, 4개의 값이 나옴
print(torch.max(A, dim = 0))

# 1번째 dimension 방향으로 각각 가장 큰 값.
# 즉, 3개의 값이 나옴
print(torch.max(A, dim = 1)) 

# 0번째 dimension 방향으로 각각 가장 큰 값.
# 그리고 dimension은 유지
print(torch.max(A, dim = 0, keepdim = True)) 

# 1번째 dimension 방향으로 각각 가장 큰 값.
# 그리고 dimension은 유지.
# 즉, 3x1 짜리 2D tensor
print(torch.max(A, dim = 1, keepdim = True))

tensor([[-1.1458, -0.5573, -1.5921, -1.0514],
        [-0.5857,  0.6137, -0.7344, -1.3591],
        [-0.9215,  0.3135,  0.5613,  0.8570]])
tensor(0.8570)
torch.return_types.max(
values=tensor([-0.5857,  0.6137,  0.5613,  0.8570]),
indices=tensor([1, 1, 2, 2]))
torch.return_types.max(
values=tensor([-0.5573,  0.6137,  0.8570]),
indices=tensor([1, 1, 3]))
torch.return_types.max(
values=tensor([[-0.5857,  0.6137,  0.5613,  0.8570]]),
indices=tensor([[1, 1, 2, 2]]))
torch.return_types.max(
values=tensor([[-0.5573],
        [ 0.6137],
        [ 0.8570]]),
indices=tensor([[1],
        [1],
        [3]]))


In [ ]:
# torch.argmax()
A = torch.randn(3,4)
print(A)

print(torch.argmax(A))

# 각 열에서 가장 큰 값이 존재하는 인덱스
print(torch.argmax(A,dim=0))

# 각 행에서 가장 큰 값이 존재하는 인덱스
print(torch.argmax(A,dim=1))

tensor([[ 0.2271, -0.8179,  1.3430,  0.3997],
        [ 0.1429,  0.3335,  0.0851, -1.7514],
        [ 1.9710, -1.3510,  1.1681, -0.3809]])
tensor(8)
tensor([2, 1, 0, 0])
tensor([2, 1, 0])


In [ ]:
# torch.sort()
a = torch.randn(6,1)
print(a)

a_sorted = torch.sort(a, dim = 0) # 기본 오름차순 정렬
print(a_sorted)

a_sorted = torch.sort(a, dim = 0, descending = True) # 내림차순 정렬
print(a_sorted)


tensor([[-1.8518],
        [ 0.9623],
        [-0.7140],
        [ 1.4051],
        [-1.3720],
        [-0.2899]])
torch.return_types.sort(
values=tensor([[-1.8518],
        [-1.3720],
        [-0.7140],
        [-0.2899],
        [ 0.9623],
        [ 1.4051]]),
indices=tensor([[0],
        [4],
        [2],
        [5],
        [1],
        [3]]))
torch.return_types.sort(
values=tensor([[ 1.4051],
        [ 0.9623],
        [-0.2899],
        [-0.7140],
        [-1.3720],
        [-1.8518]]),
indices=tensor([[3],
        [1],
        [5],
        [2],
        [4],
        [0]]))


In [ ]:
# torch.mean()
t = 2 * torch.rand(5, 2) - 1
print(t)

# 텐서의 전체 평균  
t1 = torch.mean(t)
print(t1)
print()

t2 = torch.mean(t, axis = 0)
t22 = torch.mean(t, dim = 0)
t222 = torch.mean(t, dim = 0, keepdim = True)
print(t2)
print(t22)
print(t222)
print()

t3 = torch.mean(t, axis = 1)
t33 = torch.mean(t, dim = 1)
t333 = torch.mean(t, dim = 1, keepdim = True)
print(t3)
print(t33)
print(t333)

tensor([[-0.5418, -0.3837],
        [-0.5920,  0.6408],
        [ 0.9517,  0.5600],
        [ 0.7042,  0.1876],
        [-0.2711,  0.8541]])
tensor(0.2110)

tensor([0.0502, 0.3717])
tensor([0.0502, 0.3717])
tensor([[0.0502, 0.3717]])

tensor([-0.4627,  0.0244,  0.7558,  0.4459,  0.2915])
tensor([-0.4627,  0.0244,  0.7558,  0.4459,  0.2915])
tensor([[-0.4627],
        [ 0.0244],
        [ 0.7558],
        [ 0.4459],
        [ 0.2915]])


In [ ]:
# torch.reshape()
A = torch.randint(1, 5, size = (12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B = A.reshape(2, 2, 3)
print(B)
print(B.ndim) # 3 차원 행렬이다

t = torch.zeros(10)
print(t)
print(t.shape)

t_reshape = t.reshape(2, 5)
print(t_reshape)
print(t_reshape.shape)

tensor([1, 1, 2, 3, 4, 1, 3, 4, 4, 2, 2, 4])
torch.Size([12])
tensor([[[1, 1, 2],
         [3, 4, 1]],

        [[3, 4, 4],
         [2, 2, 4]]])
3
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


In [ ]:
A = torch.arange(20,)
print(A.shape)
print(A)

print(A.reshape(4,5))
print(A.reshape(4, -1).shape) # 4개 행이 되도록 열의 수를 자동으로 맞춤
print(A.reshape(2, 5,-1).shape) # 2 x 5 x 2
print(A.reshape(2, -1, 5).shape)
print(A.reshape(1, -1).shape) # 2차원 행 벡터
print(A.reshape(-1, 1).shape) # 2차원 열 벡터

torch.Size([20])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [ ]:
# 내적
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 1])
print(torch.sum(a*b))

a = a.reshape(3,1) # 3x1 벡터
b = b.reshape(3,1) # 3x1 벡터
print(a.transpose(1,0)@b) # 1번째 dim, 0번째 dim 자리 바꾸고 @ b
print(a.permute(1,0)@b) # 0번째에는 1번째 값, 1번째에는 0번째 값으로 자리 바꾸고 @ b    
print(a.T@b)
print(a.t()@b)

A = torch.randn(4,3,6)
print(A.permute(1,2,0).shape)
print(A.transpose(2,1).shape) # transpose 는 둘끼리 자리 바꾸기만 가능
print(A.transpose(1,2).shape) # 즉, 위와 같음

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([3, 6, 4])
torch.Size([4, 6, 3])
torch.Size([4, 6, 3])


In [16]:
x = torch.randn(2, 3, 4, 5, 6)
print(x.shape)

print(x[1, 2, :, :, :].shape)
print(x[1, 2, ...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.

print(x[:, :, :, :, 3].shape)
print(x[..., 3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.

print(x[1, :, :, 3, :].shape)
print(x[1, ..., 3, :].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([2, 3, 4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [ ]:
A = torch.ones(3, 4)
B = torch.zeros(3, 4)

C = torch.vstack([A, B])
D = torch.hstack([A, B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다. (A,B 사이즈 (2,3,4)로 추가 해보기)
E = torch.cat([A, B], dim = 0) # 0번째 차원에 대해서 concat. 즉, 6x4 됨
F = torch.cat([A, B], dim = 1) # 1번째 차원에 대해서 concat. 즉, 3x8 됨
# cat만 쓰면 vstack, hstack 안써도 된다.

print(C, C.shape)
print(D, D.shape)
print(E, E.shape)
print(F, F.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.Size([6, 4])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]]) torch.Size([3, 8])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.Size([6, 4])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]]) torch.Size([3, 8])


In [ ]:
# squeeze
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, dim = 2)

print(t.shape)
print(t_sqz.shape)

A = torch.randn(1,1,1,3,1,1,1,4,1,1,1)

print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(dim=(0,2,4,5)).shape) # 0, 2, 4, 5번째 차원 제거

torch.Size([1, 2, 1, 4, 1])
torch.Size([1, 2, 4, 1])
torch.Size([1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1])
torch.Size([3, 4])
torch.Size([1, 3, 1, 4, 1, 1, 1])


In [ ]:
# unsqueeze
A = torch.randn(3,4)

print(A.unsqueeze(dim=0).shape) # 0번째에 가상의 차원 추가
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)

# 위와 동일, 그러나 귀찮음
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

# unsqueeze 활용
# A와 B를 2x3x4로 쌓고 싶을 때
A = torch.ones(3,4)
B = torch.zeros(3,4)
A = A.unsqueeze(dim=0)
B = B.unsqueeze(dim=0)
C = torch.cat([A,B], dim=0)

print(C)
print(C.shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [ ]:
# stack
A = torch.ones(3, 4)
B = torch.zeros(3, 4)
C = torch.stack([A, B])

print(C)
# unsqueeze 안하고 stack 으로 하면 되긴 함.
# (차원을 추가(default는 dim=0에)해서 쌓아줌)
# 근데 차원을 추가해서 쌓는 방식이다보니 A,B shape이 완전히 일치해야 함.
# concat은 달라도 쌓을 차원 이외 차원들만 맞으면 됨

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [32]:
# clone
A = torch.tensor([[1,2],[3,4]])
B = A.clone()
B[0,0]=100

print(B)
print(A)

# 이건 A, B의 주소가 같아서 동시에 바뀜
A = torch.tensor([[1,2],[3,4]])
B = A
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])
tensor([[100,   2],
        [  3,   4]])
tensor([[100,   2],
        [  3,   4]])


In [ ]:
# 행렬곱 @
A = torch.randn(5,7)
B = torch.randn(7,10)
C = A @ B
print(C.shape) # 5x10

A = torch.randn(32,5,7)
B = torch.randn(32,7,10)
C = A @ B
print(C.shape) # 32x5x10

# 이런것도 가능하긴 함.
# B 7x10을 32개로 복제해서 행렬곱
A = torch.randn(32, 5, 7)
B = torch.randn(7, 10)
C = A @ B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])
torch.Size([32, 5, 10])


In [ ]:
import numpy as np
import torch

a = np.array([1,2,3])
b = torch.tensor([1,2,3])

# numpy에서 tensor로 변환
A = torch.tensor(a)
A1 = torch.from_numpy(a)

# tensor에서 numpy로 변환
B = b.numpy()
B1 = np.array(b)

print(type(A))
print(type(A1))

print(type(B))
print(type(B1))


<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# 1시간 14분